# loading

In [9]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from collections import defaultdict
from surprise import SVD, Dataset, Reader, accuracy
from surprise.model_selection import train_test_split as surprise_split
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
BASE_PATH = "D:/..amikom/6th/data-mining-project"
cbf_df  = pd.read_csv(f"{BASE_PATH}/cbf_final.csv", index_col=0)
ratings = pd.read_csv(f"{BASE_PATH}/goodbooks-10k/ratings.csv")
books   = pd.read_csv(f"{BASE_PATH}/books_clean.csv", index_col=0)

# cb with word2vec

In [3]:
cbf_df.head()

,id,book_id,title,authors,decade_year,tag_name,tag_length
0,1,2767052,"The Hunger Games (The Hunger Games, #1)",author_suzanne_collins,decade_2000s,"young_adult, fiction, dystopian, dystopia, fan...",100
1,2,3,Harry Potter and the Sorcerer's Stone (Harry P...,author_jk_rowling author_mary_grandpr,decade_1990s,"fantasy, young_adult, fiction, harry_potter, s...",96
2,3,41865,"Twilight (Twilight, #1)",author_stephenie_meyer,decade_2000s,"young_adult, fantasy, vampire, fiction, parano...",109
3,4,2657,To Kill a Mockingbird,author_harper_lee,decade_1960s,"classic, classic, historical_fiction, school, ...",107
4,5,4671,The Great Gatsby,author_f_scott_fitzgerald,decade_1920s,"classic, fiction, classic, literature, school,...",115

In [4]:
cbf_df.drop(columns=['book_id'], inplace=True)
cbf_df.rename(columns={'id': 'book_id'}, inplace=True)
cbf_df.head()

,book_id,title,authors,decade_year,tag_name,tag_length
0,1,"The Hunger Games (The Hunger Games, #1)",author_suzanne_collins,decade_2000s,"young_adult, fiction, dystopian, dystopia, fan...",100
1,2,Harry Potter and the Sorcerer's Stone (Harry P...,author_jk_rowling author_mary_grandpr,decade_1990s,"fantasy, young_adult, fiction, harry_potter, s...",96
2,3,"Twilight (Twilight, #1)",author_stephenie_meyer,decade_2000s,"young_adult, fantasy, vampire, fiction, parano...",109
3,4,To Kill a Mockingbird,author_harper_lee,decade_1960s,"classic, classic, historical_fiction, school, ...",107
4,5,The Great Gatsby,author_f_scott_fitzgerald,decade_1920s,"classic, fiction, classic, literature, school,...",115

In [5]:
cbf_df['tag_name_clean'] = cbf_df['tag_name'].str.replace(',', ' ')

cbf_df['soup'] = cbf_df['authors'] + " " + cbf_df['decade_year'] + " " + cbf_df['tag_name_clean']

tokenized_soup = cbf_df['soup'].apply(lambda x: x.split())

w2v_model = Word2Vec(
    sentences=tokenized_soup,
    vector_size=100, window=5, min_count=1, workers=4, epochs=10
)

def get_book_vector(tokens, model):
    vecs = [model.wv[w] for w in tokens if w in model.wv]
    return np.mean(vecs, axis=0) if vecs else np.zeros(model.vector_size)

book_vectors = np.array([get_book_vector(t, w2v_model) for t in tokenized_soup])
cbf_sim_matrix = cosine_similarity(book_vectors)

# Lookup maps
cbf_title_to_idx = {title: i for i, title in enumerate(cbf_df['title'])}
cbf_id_to_idx    = {bid: i   for i, bid   in enumerate(cbf_df['book_id'])}

In [6]:
cbf_df.head()

,book_id,title,authors,decade_year,tag_name,tag_length,tag_name_clean,soup
0,1,"The Hunger Games (The Hunger Games, #1)",author_suzanne_collins,decade_2000s,"young_adult, fiction, dystopian, dystopia, fan...",100,young_adult fiction dystopian dystopia fan...,author_suzanne_collins decade_2000s young_adul...
1,2,Harry Potter and the Sorcerer's Stone (Harry P...,author_jk_rowling author_mary_grandpr,decade_1990s,"fantasy, young_adult, fiction, harry_potter, s...",96,fantasy young_adult fiction harry_potter s...,author_jk_rowling author_mary_grandpr decade_1...
2,3,"Twilight (Twilight, #1)",author_stephenie_meyer,decade_2000s,"young_adult, fantasy, vampire, fiction, parano...",109,young_adult fantasy vampire fiction parano...,author_stephenie_meyer decade_2000s young_adul...
3,4,To Kill a Mockingbird,author_harper_lee,decade_1960s,"classic, classic, historical_fiction, school, ...",107,classic classic historical_fiction school ...,author_harper_lee decade_1960s classic classi...
4,5,The Great Gatsby,author_f_scott_fitzgerald,decade_1920s,"classic, fiction, classic, literature, school,...",115,classic fiction classic literature school ...,author_f_scott_fitzgerald decade_1920s classic...

In [7]:
tokenized_soup

0       [author_suzanne_collins, decade_2000s, young_a...
1       [author_jk_rowling, author_mary_grandpr, decad...
2       [author_stephenie_meyer, decade_2000s, young_a...
3       [author_harper_lee, decade_1960s, classic, cla...
4       [author_f_scott_fitzgerald, decade_1920s, clas...
                              ...
8725    [author_herman_melville, decade_1920s, classic...
8726    [author_ilona_andrews, decade_2010s, urban_fan...
8727    [author_robert_a_caro, decade_1990s, biography...
8728    [author_patrick_obrian, decade_1970s, historic...
8729    [author_peggy_orenstein, decade_2010s, non_fic...
Name: soup, Length: 8730, dtype: object

In [8]:
book_vectors

array([[-0.23554282, -0.28430393,  0.9058518 , ...,  0.3080037 ,
         0.5854063 , -0.8273792 ],
       [-0.18468864, -0.12509336,  0.589062  , ...,  0.655989  ,
        -0.05979095, -0.15672   ],
       [-0.13891429, -0.49481273,  1.0352036 , ...,  0.8564809 ,
         0.45365545, -1.6935902 ],
       ...,
       [-0.18552423,  1.6020869 , -0.29409328, ..., -0.26541606,
        -0.32010373,  0.29811925],
       [-0.2607378 ,  0.6316968 ,  0.51601434, ...,  0.13679378,
        -0.01036694,  0.29398617],
       [-0.1934042 ,  1.0890583 , -0.23797621, ..., -0.11983091,
         0.09639737, -0.30895343]], dtype=float32)

In [9]:
cbf_sim_matrix

array([[0.99999994, 0.85390836, 0.8184175 , ..., 0.16171391, 0.5882348 ,
        0.26378044],
       [0.85390836, 0.9999998 , 0.72463197, ..., 0.2676177 , 0.6913161 ,
        0.2782469 ],
       [0.8184175 , 0.72463197, 1.0000001 , ..., 0.1394842 , 0.3665318 ,
        0.29730642],
       ...,
       [0.16171391, 0.2676177 , 0.1394842 , ..., 0.99999994, 0.650869  ,
        0.9298641 ],
       [0.5882348 , 0.6913161 , 0.3665318 , ..., 0.650869  , 0.9999999 ,
        0.54618526],
       [0.26378044, 0.2782469 , 0.29730642, ..., 0.9298641 , 0.54618526,
        1.        ]], dtype=float32)

In [10]:
cbf_title_to_idx

{'The Hunger Games (The Hunger Games, #1)': 0,
 "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)": 1,
 'Twilight (Twilight, #1)': 2,
 'To Kill a Mockingbird': 3,
 'The Great Gatsby': 4,
 'The Fault in Our Stars': 5,
 'The Hobbit': 6,
 'The Catcher in the Rye': 7,
 'Angels & Demons  (Robert Langdon, #1)': 8,
 'Pride and Prejudice': 9,
 'The Kite Runner': 10,
 'Divergent (Divergent, #1)': 11,
 '1984': 12,
 'Animal Farm': 13,
 'The Diary of a Young Girl': 14,
 'The Girl with the Dragon Tattoo (Millennium, #1)': 15,
 'Catching Fire (The Hunger Games, #2)': 16,
 'Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)': 17,
 'The Fellowship of the Ring (The Lord of the Rings, #1)': 18,
 'Mockingjay (The Hunger Games, #3)': 19,
 'Harry Potter and the Order of the Phoenix (Harry Potter, #5)': 20,
 'The Lovely Bones': 21,
 'Harry Potter and the Chamber of Secrets (Harry Potter, #2)': 22,
 'Harry Potter and the Goblet of Fire (Harry Potter, #4)': 23,
 'Harry Potter and the Deathly Hallows (Harry Potter, #7)': 24,
 'The Da Vinci Code (Robert Langdon, #2)': 25,
 'Harry Potter and the Half-Blood Prince (Harry Potter, #6)': 26,
 'Lord of the Flies': 27,
 'Romeo and Juliet': 28,
 'Gone Girl': 29,
 'The Help': 30,
 'Of Mice and Men': 31,
 'Memoirs of a Geisha': 32,
 'Fifty Shades of Grey (Fifty Shades, #1)': 33,
 'The Alchemist': 34,
 'The Giver (The Giver, #1)': 35,
 'The Lion, the Witch, and the Wardrobe (Chronicles of Narnia, #1)': 36,
 "The Time Traveler's Wife": 37,
 'A Game of Thrones (A Song of Ice and Fire, #1)': 38,
 'Eat, Pray, Love': 39,
 'The Lightning Thief (Percy Jackson and the Olympians, #1)': 40,
 'Little Women (Little Women, #1)': 41,
 'Jane Eyre': 42,
 'The Notebook (The Notebook, #1)': 43,
 'Water for Elephants': 44,
 'The Book Thief': 45,
 'New Moon (Twilight, #2)': 46,
 'Where the Sidewalk Ends': 47,
 'City of Bones (The Mortal Instruments, #1)': 48,
 'Eclipse (Twilight, #3)': 49,
 'Eragon (The Inheritance Cycle, #1)': 50,
 "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)": 51,
 'Brave New World': 52,
 'Breaking Dawn (Twilight, #4)': 53,
 'The Secret Life of Bees': 54,
 'The Adventures of Huckleberry Finn': 55,
 "Charlotte's Web": 56,
 'The Curious Incident of the Dog in the Night-Time': 57,
 'The Girl on the Train': 58,
 'The Golden Compass (His Dark Materials, #1)': 59,
 'Wuthering Heights': 60,
 "My Sister's Keeper": 61,
 'Slaughterhouse-Five': 62,
 'Gone with the Wind': 63,
 'A Thousand Splendid Suns': 64,
 'The Perks of Being a Wallflower': 65,
 'Insurgent (Divergent, #2)': 66,
 "Ender's Game (Ender's Saga, #1)": 67,
 'Frankenstein': 68,
 'The Shining (The Shining #1)': 69,
 'The Host (The Host, #1)': 70,
 'Looking for Alaska': 71,
 "Bridget Jones's Diary (Bridget Jones, #1)": 72,
 'Sense and Sensibility': 73,
 'Holes (Holes, #1)': 74,
 'The Devil Wears Prada (The Devil Wears Prada, #1)': 75,
 'The Odyssey': 76,
 'The Little Prince': 77,
 'The Glass Castle': 78,
 'Into the Wild': 79,
 'A Tale of Two Cities': 80,
 'The Giving Tree': 81,
 'A Time to Kill': 82,
 'Night (The Night Trilogy #1)': 83,
 'Paper Towns': 84,
 'The Princess Bride ': 85,
 'The Outsiders': 86,
 'The Maze Runner (Maze Runner, #1)': 87,
 'Freakonomics: A Rogue Economist Explores the Hidden Side of Everything (Freakonomics, #1)': 88,
 'The Secret Garden': 89,
 'One Hundred Years of Solitude': 90,
 'The Picture of Dorian Gray': 91,
 'Fifty Shades Freed (Fifty Shades, #3)': 92,
 'Dracula': 93,
 'The Girl Who Played with Fire (Millennium, #2)': 94,
 'Fifty Shades Darker (Fifty Shades, #2)': 95,
 'The Poisonwood Bible': 96,
 'Me Talk Pretty One Day': 97,
 'Where the Wild Things Are': 98,
 'The Count of Monte Cristo': 99,
 'The Road': 100,
 'Allegiant (Divergent, #3)': 101,
 'Bossypants': 102,
 'A Walk to Remember': 103,
 'Confessions of a Shopaholic (Shopaholic, #1)': 104,
 'Les Misérables': 105,
 'A Clash of Kings  (A Song of Ice and Fire, #2)': 106,
 "The Memory Keeper's Daughter": 107,
 'Me Before You (Me Before You, #1)': 108,
 'Catch-22': 109,
 'Tuesdays with Morrie': 110,
 'Middlesex': 111,
 'The Adventures of Tom Sawyer': 112,
 'A Wrinkle in Time (A Wrinkle in Time Quintet, #1)': 113,
 'The Joy Luck Club': 114,
 "The Handmaid's Tale": 115,
 'The Sisterhood of the Traveling Pants (Sisterhood, #1)': 116,
 'Lolita': 117,
 'Wicked: The Life and Times of the Wicked Witch of the West (The Wicked Years, #1)': 118,
 'The Firm (Penguin Readers, Level 5)': 119,
 'Room': 120,
 'Hamlet': 121,
 'Dune (Dune Chronicles #1)': 122,
 'The Tipping Point: How Little Things Can Make a Big Difference': 123,
 'Steve Jobs': 124,
 "One Flew Over the Cuckoo's Nest": 125,
 'The Old Man and the Sea': 126,
 'The Grapes of Wrath': 127,
 'Anne of Green Gables (Anne of Green Gables, #1)': 128,
 'City of Glass (The Mortal Instruments, #3)': 129,
 'A Storm of Swords (A Song of Ice and Fire, #3)': 130,
 'Divine Secrets of the Ya-Ya Sisterhood': 131,
 'Outlander (Outlander, #1)': 132,
 'The Scarlet Letter': 133,
 'Miss Peregrine’s Home for Peculiar Children (Miss Peregrine’s Peculiar Children, #1)': 134,
 "The Girl Who Kicked the Hornet's Nest (Millennium, #3)": 135,
 'The Martian': 136,
 'The Pillars of the Earth (The Kingsbridge Series, #1)': 137,
 'All the Light We Cannot See': 138,
 'Unbroken: A World War II Story of Survival, Resilience, and Redemption': 139,
 'Deception Point': 140,
 'The Goldfinch': 141,
 'Thirteen Reasons Why': 142,
 'Girl with a Pearl Earring': 143,
 'If I Stay (If I Stay, #1)': 144,
 'The Red Tent': 145,
 'The Sea of Monsters (Percy Jackson and the Olympians, #2)': 146,
 'Dear John': 147,
 'City of Ashes (The Mortal Instruments, #2)': 148,
 'Macbeth': 149,
 'The Two Towers (The Lord of the Rings, #2)': 150,
 'Something Borrowed (Darcy & Rachel, #1)': 151,
 'Green Eggs and Ham': 152,
 'Charlie and the Chocolate Factory (Charlie Bucket, #1)': 153,
 'The Battle of the Labyrinth (Percy Jackson and the Olympians, #4)': 154,
 'Great Expectations': 155,
 'The Return of the King (The Lord of the Rings, #3)': 156,
 'The Stranger': 2249,
 'The Lost Hero (The Heroes of Olympus, #1)': 158,
 'Eleanor & Park': 159,
 'A Feast for Crows (A Song of Ice and Fire, #4)': 160,
 'Matched (Matched, #1)': 161,
 'American Gods (American Gods, #1)': 162,
 'The Stand': 163,
 'The Last Song': 164,
 'Digital Fortress': 165,
 'Emma': 166,
 'Anna Karenina': 167,
 'A Clockwork Orange': 168,
 'The Shack': 169,
 'The Last Olympian (Percy Jackson and the Olympians, #5)': 170,
 'It': 171,
 'Crime and Punishment': 172,
 'The Bell Jar': 173,
 "Angela's Ashes (Frank McCourt, #1)": 174,
 'Siddhartha': 175,
 'In Cold Blood': 176,
 'Beautiful Creatures (Caster Chronicles, #1)': 177,
 'Clockwork Angel (The Infernal Devices, #1)': 178,
 'Matilda': 179,
 'The Night Circus': 180,
 'The Other Boleyn Girl (The Plantagenet and Tudor Novels, #9)': 181,
 'Uglies (Uglies, #1)': 182,
 'A Dance with Dragons (A Song of Ice and Fire, #5)': 183,
 'The Lord of the Rings (The Lord of the Rings, #1-3)': 184,
 'Wild: From Lost to Found on the Pacific Crest Trail': 185,
 'Watchmen': 186,
 'The Name of the Wind (The Kingkiller Chronicle, #1)': 187,
 'Outliers: The Story of Success': 188,
 'Moby-Dick or, The Whale': 189,
 'The Guernsey Literary and Potato Peel Pie Society': 190,
 'Fight Club': 191,
 'Dead Until Dark (Sookie Stackhouse, #1)': 192,
 'The Color Purple': 193,
 "Marley and Me: Life and Love With the World's Worst Dog": 194,
 'And Then There Were None': 195,
 'The Lost Symbol (Robert Langdon, #3)': 196,
 'Hush, Hush (Hush, Hush, #1)': 197,
 'Beautiful Disaster (Beautiful, #1)': 198,
 'Interview with the Vampire (The Vampire Chronicles, #1)': 199,
 'The Selection (The Selection, #1)': 200,
 'One for the Money (Stephanie Plum, #1)': 201,
 'The Immortal Life of Henrietta Lacks': 202,
 'The Silence of the Lambs  (Hannibal Lecter, #2)': 203,
 'Vampire Academy (Vampire Academy, #1)': 204,
 'Blink: The Power of Thinking Without Thinking': 205,
 'Atonement': 206,
 'The Metamorphosis': 207,
 "The Titan's Curse (Percy Jackson and the Olympians, #3)": 208,
 'Ready Player One': 209,
 'The Art of Racing in the Rain': 210,
 'The Devil in the White City: Murder, Magic, and Madness at the Fair That Changed America': 211,
 'Bared to You (Crossfire, #1)': 212,
 'The Chronicles of Narnia (Chronicles of Narnia, #1-7)': 213,
 'Twilight: The Complete Illustrated Movie Companion': 214,
 'A Child Called "It" (Dave Pelzer #1)': 215,
 'The Bourne Identity (Jason Bourne, #1)': 216,
 'Artemis Fowl (Artemis Fowl, #1)': 217,
 'Fallen (Fallen, #1)': 218,
 'East of Eden': 219,
 'Dark Places': 220,
 'The Client': 221,
 'The Nanny Diaries (Nanny, #1)': 222,
 "Alice's Adventures in Wonderland & Through the Looking-Glass": 223,
 'Persuasion': 224,
 "Sarah's Key": 225,
 'The Gunslinger (The Dark Tower, #1)': 226,
 'Love in the Time of Cholera': 227,
 'Speak': 228,
 "The Husband's Secret": 229,
 'Into Thin Air: A Personal Account of the Mount Everest Disaster': 230,
 'Running with Scissors': 231,
 'World War Z: An Oral History of the Zombie War': 232,
 'Inferno (Robert Langdon, #4)': 233,
 'Number the Stars': 234,
 'Along Came a Spider (Alex Cross, #1)': 235,
 'Misery': 236,
 'Sharp Objects': 237,
 'Bridge to Terabithia': 238,
 'Marked (House of Night, #1)': 239,
 'The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change': 240,
 "A Midsummer Night's Dream": 241,
 'Extremely Loud and Incredibly Close': 242,
 'Wonder': 243,
 'The Cat in the Hat': 244,
 'Cinder (The Lunar Chronicles, #1)': 245,
 "The Cuckoo's Calling (Cormoran Strike, #1)": 246,
 'Shiver (The Wolves of Mercy Falls, #1)': 247,
 'Atlas Shrugged': 248,
 "Three Cups of Tea: One Man's Mission to Promote Peace ... One School at a Time": 249,
 'Alice in Wonderland': 250,
 'The Shadow of the Wind (The Cemetery of Forgotten Books,  #1)': 251,
 'The Scorch Trials (Maze Runner, #2)': 252,
 'How to Win Friends and Influence People': 253,
 'Under the Tuscan Sun': 254,
 'Big Little Lies': 255,
 'Ella Enchanted': 256,
 'The Sun Also Rises': 257,
 'A Tree Grows in Brooklyn': 258,
 'Kiss the Girls (Alex Cross, #2)': 259,
 'The Nightingale': 260,
 'Never Let Me Go': 261,
 'P.S. I Love You': 262,
 'Rebecca': 263,
 'Flowers for Algernon': 264,
 'Like Water for Chocolate': 265,
 'Snow Flower and the Secret Fan': 266,
 'The Godfather': 267,
 'An Abundance of Katherines': 268,
 'Foundation (Foundation #1)': 269,
 'The Ocean at the End of the Lane': 270,
 'A Light in the Attic': 271,
 'Harry Potter and the Cursed Child - Parts One and Two (Harry Potter, #8)': 272,
 'Delirium (Delirium, #1)': 273,
 'The Pelican Brief': 274,
 'Coraline': 275,
 'Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch': 276,
 'On the Road': 277,
 'The Rosie Project (Don Tillman, #1)': 278,
 'The Lucky One': 279,
 'The Fountainhead': 280,
 'Watership Down (Watership Down, #1)': 281,
 'Is Everyone Hanging Out Without Me? (And Other Concerns)': 282,
 'Cutting for Stone': 283,
 'The Voyage of the Dawn Treader (Chronicles of Narnia, #3)': 284,
 'Treasure Island': 285,
 'The Son of Neptune (The Heroes of Olympus, #2)': 286,
 '11/22/63': 287,
 'The Very Hungry Caterpillar Board Book': 288,
 "Cat's Cradle": 289,
 'The Time Machine': 290,
 "Heaven is for Real: A Little Boy's Astounding Story of His Trip to Heaven and Back": 291,
 'The Boy in the Striped Pajamas': 292,
 'Heart of Darkness': 293,
 'Safe Haven': 294,
 'The Secret (The Secret, #1)': 295,
 'I Know This Much Is True': 296,
 'Pet Sematary': 297,
 "She's Come Undone": 298,
 "The Wise Man's Fear (The Kingkiller Chronicle, #2)": 299,
 'Can You Keep a Secret?': 300,
 'City of Fallen Angels (The Mortal Instruments, #4)': 301,
 'Good in Bed (Cannie Shapiro, #1)': 302,
 'The Thorn Birds': 303,
 'The Graveyard Book': 304,
 'The Light Between Oceans': 305,
 'Inkheart (Inkworld, #1)': 306,
 'Who Moved My Cheese?': 307,
 'A Walk in the Woods': 308,
 'I Know Why the Caged Bird Sings': 309,
 'Orphan Train': 310,
 'City of Lost Souls (The Mortal Instruments, #5)': 311,
 "Where'd You Go, Bernadette": 312,
 'Neverwhere': 313,
 'The Unbearable Lightness of Being': 314,
 'Fangirl': 315,
 'A Prayer for Owen Meany': 316,
 'White Oleander': 317,
 'Legend (Legend, #1)': 318,
 'Nineteen Minutes': 319,
 'The Last Lecture': 320,
 'The Eye of the World (Wheel of Time, #1)': 321,
 'The Pact': 7715,
 "The Magician's Nephew (Chronicles of Narnia, #6)": 323,
 'Still Alice': 324,
 'Reflected in You (Crossfire, #2)': 325,
 'James and the Giant Peach': 326,
 "1st to Die (Women's Murder Club, #1)": 327,
 "The Ultimate Hitchhiker's Guide to the Galaxy": 328,
 'One Day': 329,
 'Goodnight Moon': 330,
 'I Am Number Four (Lorien Legacies, #1)': 331,
 'The Iliad': 332,
 'The Casual Vacancy': 333,
 'The Runaway Jury': 334,
 'Naked': 335,
 'Eldest (The Inheritance Cycle, #2)': 336,
 'The Wonderful Wizard of Oz (Oz, #1)': 337,
 'Prince Caspian (Chronicles of Narnia, #2)': 338,
 'We Were Liars': 339,
 "'Salem's Lot": 1237,
 'Fear and Loathing in Las Vegas': 341,
 'Clockwork Prince (The Infernal Devices, #2)': 342,
 'Yes Please': 343,
 'Othello': 344,
 'Beloved': 345,
 'Graceling (Graceling Realm, #1)': 346,
 'The Bad Beginning (A Series of Unfortunate Events, #1)': 347,
 'All Quiet on the Western Front': 348,
 "Oh, The Places You'll Go!": 349,
 'And the Mountains Echoed': 350,
 'Do Androids Dream of Electric Sheep?': 351,
 'Oliver Twist': 352,
 'The Screwtape Letters': 353,
 'Anna and the French Kiss (Anna and the French Kiss, #1)': 354,
 'How the Grinch Stole Christmas!': 355,
 'V for Vendetta': 356,
 'John Adams': 357,
 'Odd Thomas (Odd Thomas, #1)': 358,
 'The Subtle Knife (His Dark Materials, #2)': 359,
 'Stargirl (Stargirl, #1)': 360,
 'The Red Pyramid (Kane Chronicles, #1)': 361,
 'Stranger in a Strange Land': 362,
 'Dress Your Family in Corduroy and Denim': 363,
 'The BFG': 364,
 'A Short History of Nearly Everything': 365,
 'The Call of the Wild': 366,
 'The Death Cure (Maze Runner, #3)': 367,
 'Stardust': 368,
 'The Namesake': 369,
 'A Discovery of Witches (All Souls Trilogy, #1)': 370,
 'Norwegian Wood': 371,
 'Where the Heart Is': 372,
 'Will Grayson, Will Grayson': 373,
 'A Million Little Pieces': 374,
 'Frostbite (Vampire Academy, #2)': 375,
 "Quiet: The Power of Introverts in a World That Can't Stop Talking": 376,
 'Island of the Blue Dolphins (Island of the Blue Dolphins, #1)': 377,
 'The Crucible': 378,
 "Hatchet (Brian's Saga, #1)": 379,
 'The Final Empire (Mistborn, #1)': 380,
 'The Strange Case of Dr. Jekyll and Mr. Hyde': 381,
 'The Lorax': 382,
 'Diary of a Wimpy Kid (Diary of a Wimpy Kid, #1)': 383,
 'Throne of Glass (Throne of Glass, #1)': 384,
 'Shadow Kiss (Vampire Academy, #3)': 385,
 'For Whom the Bell Tolls': 386,
 'Hotel on the Corner of Bitter and Sweet': 387,
 'Perfume: The Story of a Murderer': 388,
 'Fast Food Nation: The Dark Side of the All-American Meal': 389,
 'The Tales of Beedle the Bard': 390,
 'Neuromancer': 391,
 'A Farewell to Arms': 392,
 'The Tell-Tale Heart and Other Writings': 393,
 'The Art of War': 394,
 'Defending Jacob': 395,
 'Breakfast of Champions': 396,
 'The New Drawing on the Right Side of the Brain': 397,
 'Bel Canto': 398,
 'Guns, Germs, and Steel: The Fates of Human Societies': 399,
 'Things Fall Apart (The African Trilogy, #1)': 400,
 'The Undomestic Goddess': 401,
 'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate': 402,
 'Little Bee': 403,
 'Evermore (The Immortals, #1)': 404,
 'The Witches': 405,
 'The Thirteenth Tale': 406,
 'Spirit Bound (Vampire Academy, #5)': 407,
 'Blood Promise (Vampire Academy, #4)': 408,
 'Message in a Bottle': 409,
 'The Paris Wife': 410,
 'Harry Potter Boxset (Harry Potter, #1-7)': 411,
 'The Elite (The Selection, #2)': 412,
 'The Name of the Rose': 413,
 'Go Ask Alice': 414,
 'A Confederacy of Dunces': 415,
 'The Importance of Being Earnest': 416,
 'The Mark of Athena (The Heroes of Olympus, #3)': 417,
 'The Color of Magic (Discworld, #1; Rincewind #1)': 418,
 'Kafka on the Shore': 419,
 'Red Dragon (Hannibal Lecter, #1)': 420,
 'I, Robot (Robot #0.1)': 421,
 'Dark Lover (Black Dagger Brotherhood, #1)': 422,
 'Crescendo (Hush, Hush, #2)': 423,
 'Before I Fall': 424,
 'The God of Small Things': 425,
 'The Invention of Wings': 426,
 'What Alice Forgot': 427,
 'A Brief History of Time': 428,
 'Fall of Giants (The Century Trilogy, #1)': 429,
 'Under the Dome': 430,
 'Snow Crash': 431,
 'Just Listen': 432,
 'Winnie-the-Pooh (Winnie-the-Pooh, #1)': 433,
 'Before I Go to Sleep': 434,
 'A Study in Scarlet': 435,
 'Brisingr (The Inheritance Cycle, #3)': 436,
 'The Purpose Driven Life: What on Earth Am I Here for?': 437,
 'Betrayed (House of Night, #2)': 438,
 'Storm Front (The Dresden Files, #1)': 439,
 'Northanger Abbey': 440,
 'The 5th Wave (The 5th Wave, #1)': 441,
 'Cold Mountain': 442,
 'If You Give a Mouse a Cookie': 443,
 'Something Blue (Darcy & Rachel, #2)': 444,
 'A Streetcar Named Desire': 445,
 'The Historian': 446,
 'Station Eleven': 447,
 'A Man Called Ove': 448,
 'Clockwork Princess (The Infernal Devices, #3)': 449,
 'The Good Earth (House of Earth, #1)': 450,
 'Ways of Seeing': 451,
 'Dragonfly in Amber (Outlander, #2)': 452,
 'Holy Bible: King James Version': 453,
 'The Hobbit: Graphic Novel': 454,
 'The Brief Wondrous Life of Oscar Wao': 455,
 'Their Eyes Were Watching God': 456,
 'Fantastic Beasts and Where to Find Them': 457,
 'I Am Malala: The Story of the Girl Who Stood Up for Education and Was Shot by the Taliban': 458,
 'Mansfield Park': 459,
 "Man's Search for Meaning": 460,
 'In the Woods (Dublin Murder Squad, #1)': 461,
 'The God Delusion': 462,
 'Where She Went (If I Stay, #2)': 463,
 'The World According to Garp': 464,
 'Killing Floor (Jack Reacher, #1)': 465,
 'Robinson Crusoe': 466,
 'The Prince': 467,
 'The Amber Spyglass (His Dark Materials, #3)': 468,
 "Wizard's First Rule (Sword of Truth, #1)": 469,
 'The Kitchen House': 470,
 'Franny and Zooey': 471,
 'Choke': 472,
 'The Brothers Karamazov': 473,
 'The City of Ember (Book of Ember, #1)': 474,
 'The Green Mile': 475,
 'The Prophet': 476,
 "Maus I: A Survivor's Tale: My Father Bleeds History (Maus, #1)": 477,
 'Untamed (House of Night, #4)': 478,
 "Speaker for the Dead (Ender's Saga, #2)": 479,
 'Mere Christianity': 480,
 'The Secret History': 481,
 'A Heartbreaking Work of Staggering Genius': 482,
 "The Clan of the Cave Bear (Earth's Children, #1)": 483,
 'Black Beauty': 484,
 'War and Peace': 485,
 'American Psycho': 486,
 'The Princess Diaries (The Princess Diaries, #1)': 487,
 "The No. 1 Ladies' Detective Agency  (No. 1 Ladies' Detective Agency, #1)": 488,
 'The Walking Dead, Vol. 01: Days Gone Bye': 489,
 '2001: A Space Odyssey (Space Odyssey, #1)': 490,
 'Redeeming Love': 491,
 'Left Behind (Left Behind, #1)': 492,
 'The One (The Selection, #3)': 493,
 'The Hunger Games Trilogy Boxset (The Hunger Games, #1-3)': 494,
 'Nickel and Dimed: On (Not) Getting By in America': 495,
 'Remember Me?': 496,
 'The Great Hunt (Wheel of Time, #2)': 497,
 'Postmortem (Kay Scarpetta, #1)': 498,
 'The Complete Stories and Poems': 499,
 'The Hiding Place: The Triumphant True Story of Corrie Ten Boom': 500,
 'The Adventures of Sherlock Holmes': 501,
 'The Prince of Tides': 502,
 'The Amazing Adventures of Kavalier & Clay': 503,
 'Perfect Chemistry (Perfect Chemistry, #1)': 504,
 'Peter Pan': 505,
 'Pretties (Uglies, #2)': 506,
 'The Wind-Up Bird Chronicle': 507,
 'The Lincoln Lawyer (Mickey Haller, #1; Harry Bosch Universe, #16)': 508,
 'Cloud Atlas': 509,
 'The Things They Carried': 510,
 'Wall and Piece': 511,
 'Pandemonium (Delirium, #2)': 512,
 'Darkly Dreaming Dexter (Dexter, #1)': 513,
 'Living Dead in Dallas (Sookie Stackhouse, #2)': 514,
 'The Dragon Reborn (Wheel of Time, #3)': 515,
 "Gulliver's Travels": 516,
 'Much Ado About Nothing': 517,
 'Beowulf': 518,
 'Batman: Year One': 519,
 'Go Set a Watchman': 520,
 'When You Are Engulfed in Flames': 521,
 'Daughter of Smoke & Bone (Daughter of Smoke & Bone, #1)': 522,

In [11]:
cbf_id_to_idx

{1: 0,
 2: 1,
 3: 2,
 4: 3,
 5: 4,
 6: 5,
 7: 6,
 8: 7,
 9: 8,
 10: 9,
 11: 10,
 12: 11,
 13: 12,
 14: 13,
 15: 14,
 16: 15,
 17: 16,
 18: 17,
 19: 18,
 20: 19,
 21: 20,
 22: 21,
 23: 22,
 24: 23,
 25: 24,
 26: 25,
 27: 26,
 28: 27,
 29: 28,
 30: 29,
 31: 30,
 32: 31,
 33: 32,
 34: 33,
 35: 34,
 36: 35,
 37: 36,
 38: 37,
 39: 38,
 40: 39,
 41: 40,
 42: 41,
 43: 42,
 44: 43,
 46: 44,
 47: 45,
 49: 46,
 50: 47,
 51: 48,
 52: 49,
 53: 50,
 54: 51,
 55: 52,
 56: 53,
 57: 54,
 58: 55,
 59: 56,
 60: 57,
 61: 58,
 62: 59,
 63: 60,
 64: 61,
 65: 62,
 66: 63,
 67: 64,
 68: 65,
 69: 66,
 70: 67,
 71: 68,
 72: 69,
 73: 70,
 74: 71,
 75: 72,
 76: 73,
 77: 74,
 78: 75,
 79: 76,
 80: 77,
 81: 78,
 82: 79,
 83: 80,
 85: 81,
 86: 82,
 87: 83,
 88: 84,
 89: 85,
 90: 86,
 91: 87,
 92: 88,
 93: 89,
 94: 90,
 95: 91,
 96: 92,
 97: 93,
 98: 94,
 99: 95,
 100: 96,
 101: 97,
 102: 98,
 103: 99,
 104: 100,
 105: 101,
 106: 102,
 107: 103,
 108: 104,
 109: 105,
 110: 106,
 111: 107,
 112: 108,
 113: 109,
 114: 110,
 115: 111,
 116: 112,
 117: 113,
 118: 114,
 119: 115,
 120: 116,
 121: 117,
 122: 118,
 123: 119,
 124: 120,
 125: 121,
 126: 122,
 127: 123,
 128: 124,
 129: 125,
 130: 126,
 131: 127,
 133: 128,
 134: 129,
 135: 130,
 136: 131,
 137: 132,
 138: 133,
 139: 134,
 140: 135,
 141: 136,
 142: 137,
 143: 138,
 144: 139,
 145: 140,
 146: 141,
 147: 142,
 148: 143,
 149: 144,
 150: 145,
 151: 146,
 152: 147,
 153: 148,
 154: 149,
 155: 150,
 156: 151,
 157: 152,
 158: 153,
 159: 154,
 160: 155,
 161: 156,
 162: 157,
 163: 158,
 164: 159,
 165: 160,
 166: 161,
 167: 162,
 168: 163,
 169: 164,
 170: 165,
 171: 166,
 172: 167,
 173: 168,
 174: 169,
 175: 170,
 176: 171,
 177: 172,
 178: 173,
 179: 174,
 180: 175,
 181: 176,
 182: 177,
 183: 178,
 184: 179,
 185: 180,
 186: 181,
 187: 182,
 188: 183,
 189: 184,
 190: 185,
 191: 186,
 192: 187,
 193: 188,
 194: 189,
 195: 190,
 196: 191,
 197: 192,
 198: 193,
 199: 194,
 200: 195,
 201: 196,
 202: 197,
 203: 198,
 205: 199,
 206: 200,
 207: 201,
 208: 202,
 209: 203,
 210: 204,
 211: 205,
 212: 206,
 213: 207,
 214: 208,
 215: 209,
 216: 210,
 217: 211,
 218: 212,
 219: 213,
 220: 214,
 221: 215,
 222: 216,
 223: 217,
 224: 218,
 225: 219,
 226: 220,
 227: 221,
 228: 222,
 229: 223,
 230: 224,
 231: 225,
 232: 226,
 233: 227,
 234: 228,
 235: 229,
 236: 230,
 238: 231,
 239: 232,
 240: 233,
 241: 234,
 242: 235,
 243: 236,
 244: 237,
 245: 238,
 246: 239,
 247: 240,
 248: 241,
 249: 242,
 250: 243,
 251: 244,
 252: 245,
 253: 246,
 254: 247,
 255: 248,
 256: 249,
 257: 250,
 258: 251,
 259: 252,
 260: 253,
 261: 254,
 262: 255,
 263: 256,
 264: 257,
 265: 258,
 266: 259,
 267: 260,
 268: 261,
 269: 262,
 270: 263,
 271: 264,
 272: 265,
 273: 266,
 274: 267,
 275: 268,
 276: 269,
 277: 270,
 278: 271,
 279: 272,
 280: 273,
 281: 274,
 282: 275,
 283: 276,
 284: 277,
 285: 278,
 286: 279,
 287: 280,
 289: 281,
 290: 282,
 291: 283,
 292: 284,
 293: 285,
 294: 286,
 295: 287,
 296: 288,
 297: 289,
 298: 290,
 299: 291,
 300: 292,
 301: 293,
 302: 294,
 303: 295,
 304: 296,
 305: 297,
 306: 298,
 307: 299,
 308: 300,
 309: 301,
 310: 302,
 311: 303,
 312: 304,
 313: 305,
 314: 306,
 315: 307,
 316: 308,
 317: 309,
 318: 310,
 319: 311,
 320: 312,
 322: 313,
 323: 314,
 324: 315,
 325: 316,
 326: 317,
 327: 318,
 328: 319,
 329: 320,
 330: 321,
 331: 322,
 332: 323,
 333: 324,
 334: 325,
 335: 326,
 336: 327,
 337: 328,
 338: 329,
 339: 330,
 340: 331,
 341: 332,
 342: 333,
 343: 334,
 344: 335,
 345: 336,
 346: 337,
 347: 338,
 348: 339,
 349: 340,
 350: 341,
 351: 342,
 352: 343,
 353: 344,
 354: 345,
 355: 346,
 356: 347,
 357: 348,
 358: 349,
 359: 350,
 360: 351,
 361: 352,
 362: 353,
 363: 354,
 364: 355,
 365: 356,
 366: 357,
 367: 358,
 368: 359,
 369: 360,
 370: 361,
 371: 362,
 372: 363,
 373: 364,
 374: 365,
 375: 366,
 376: 367,
 377: 368,
 378: 369,
 379: 370,
 380: 371,
 381: 372,
 382: 373,
 383: 374,
 384: 375,
 385: 376,
 386: 377,
 387: 378,
 388: 379,
 389: 380,
 390: 381,
 391: 382,
 392: 383,
 393: 384,
 394: 385,
 395: 386,
 396: 387,
 397: 388,
 398: 389,
 399: 390,
 400: 391,
 401: 392,
 402: 393,
 403: 394,
 404: 395,
 405: 396,
 406: 397,
 407: 398,
 408: 399,
 410: 400,
 411: 401,
 412: 402,
 414: 403,
 415: 404,
 416: 405,
 417: 406,
 418: 407,
 419: 408,
 420: 409,
 421: 410,
 422: 411,
 423: 412,
 424: 413,
 425: 414,
 426: 415,
 427: 416,
 428: 417,
 429: 418,
 430: 419,
 431: 420,
 432: 421,
 433: 422,
 434: 423,
 435: 424,
 436: 425,
 437: 426,
 438: 427,
 439: 428,
 440: 429,
 441: 430,
 442: 431,
 443: 432,
 444: 433,
 445: 434,
 446: 435,
 447: 436,
 448: 437,
 449: 438,
 450: 439,
 451: 440,
 452: 441,
 453: 442,
 454: 443,
 455: 444,
 456: 445,
 457: 446,
 458: 447,
 459: 448,
 460: 449,
 461: 450,
 462: 451,
 463: 452,
 464: 453,
 466: 454,
 467: 455,
 468: 456,
 469: 457,
 470: 458,
 471: 459,
 472: 460,
 473: 461,
 474: 462,
 475: 463,
 476: 464,
 477: 465,
 478: 466,
 479: 467,
 480: 468,
 481: 469,
 482: 470,
 483: 471,
 484: 472,
 485: 473,
 486: 474,
 488: 475,
 489: 476,
 490: 477,
 491: 478,
 492: 479,
 493: 480,
 494: 481,
 495: 482,
 496: 483,
 497: 484,
 498: 485,
 499: 486,
 500: 487,
 501: 488,
 502: 489,
 503: 490,
 504: 491,
 505: 492,
 506: 493,
 507: 494,
 508: 495,
 509: 496,
 510: 497,
 511: 498,
 512: 499,
 513: 500,
 514: 501,
 515: 502,
 516: 503,
 517: 504,
 518: 505,
 519: 506,
 520: 507,
 521: 508,
 522: 509,
 523: 510,
 524: 511,
 525: 512,
 526: 513,
 527: 514,
 528: 515,
 529: 516,
 530: 517,
 531: 518,
 532: 519,
 533: 520,
 534: 521,
 535: 522,
 536: 523,
 537: 524,
 538: 525,
 539: 526,
 540: 527,
 541: 528,
 542: 529,
 543: 530,
 544: 531,
 545: 532,
 546: 533,
 547: 534,
 548: 535,
 549: 536,
 550: 537,
 551: 538,
 552: 539,
 554: 540,
 555: 541,
 557: 542,
 558: 543,
 559: 544,
 560: 545,
 561: 546,
 562: 547,
 563: 548,
 564: 549,
 565: 550,
 566: 551,
 567: 552,
 568: 553,
 569: 554,
 570: 555,
 571: 556,
 572: 557,
 573: 558,
 574: 559,
 575: 560,
 576: 561,
 577: 562,
 579: 563,
 580: 564,
 581: 565,
 582: 566,
 583: 567,
 584: 568,
 585: 569,
 586: 570,
 587: 571,
 588: 572,
 589: 573,
 590: 574,
 591: 575,
 592: 576,
 593: 577,
 594: 578,
 595: 579,
 596: 580,
 597: 581,
 598: 582,
 599: 583,
 600: 584,
 601: 585,
 602: 586,
 603: 587,
 604: 588,
 606: 589,
 607: 590,
 608: 591,
 609: 592,
 610: 593,
 611: 594,
 612: 595,
 613: 596,
 614: 597,
 615: 598,
 616: 599,
 617: 600,
 618: 601,
 619: 602,
 620: 603,
 621: 604,
 622: 605,
 623: 606,
 624: 607,
 625: 608,
 626: 609,
 627: 610,
 628: 611,
 629: 612,
 630: 613,
 631: 614,
 632: 615,
 633: 616,
 634: 617,
 635: 618,
 636: 619,
 637: 620,
 638: 621,
 639: 622,
 641: 623,
 642: 624,
 643: 625,
 644: 626,
 645: 627,
 646: 628,
 647: 629,
 648: 630,
 649: 631,
 650: 632,
 651: 633,
 652: 634,
 653: 635,
 654: 636,
 655: 637,
 656: 638,
 657: 639,
 658: 640,
 659: 641,
 660: 642,
 661: 643,
 662: 644,
 663: 645,
 664: 646,
 665: 647,
 666: 648,
 667: 649,
 668: 650,
 669: 651,
 670: 652,
 671: 653,
 672: 654,
 673: 655,
 674: 656,
 675: 657,
 676: 658,
 677: 659,
 678: 660,
 679: 661,
 680: 662,
 681: 663,
 682: 664,
 683: 665,
 684: 666,
 685: 667,
 686: 668,
 687: 669,
 688: 670,
 689: 671,
 690: 672,
 691: 673,
 692: 674,
 693: 675,
 694: 676,
 695: 677,
 696: 678,
 697: 679,
 698: 680,
 699: 681,
 700: 682,
 701: 683,
 702: 684,
 703: 685,
 704: 686,
 705: 687,
 706: 688,
 707: 689,
 708: 690,
 709: 691,
 710: 692,
 711: 693,
 712: 694,
 713: 695,
 714: 696,
 715: 697,
 716: 698,
 717: 699,
 718: 700,
 719: 701,
 720: 702,
 721: 703,
 722: 704,
 723: 705,
 724: 706,
 725: 707,
 726: 708,
 727: 709,
 728: 710,
 729: 711,
 730: 712,
 731: 713,
 732: 714,
 733: 715,
 734: 716,
 735: 717,
 736: 718,
 737: 719,
 739: 720,
 742: 721,
 743: 722,
 744: 723,
 745: 724,
 746: 725,
 747: 726,
 748: 727,
 749: 728,
 750: 729,
 751: 730,
 752: 731,
 753: 732,
 754: 733,
 755: 734,
 756: 735,
 757: 736,
 758: 737,
 759: 738,
 760: 739,
 761: 740,
 762: 741,
 763: 742,
 764: 743,
 765: 744,
 766: 745,
 767: 746,
 768: 747,
 769: 748,
 770: 749,
 771: 750,
 772: 751,
 773: 752,
 774: 753,
 775: 754,
 776: 755,
 777: 756,
 778: 757,
 779: 758,
 780: 759,
 781: 760,
 782: 761,
 783: 762,
 784: 763,
 785: 764,
 786: 765,
 789: 766,
 791: 767,
 792: 768,
 793: 769,
 794: 770,
 795: 771,
 796: 772,
 797: 773,
 800: 774,
 801: 775,
 802: 776,
 803: 777,
 804: 778,
 805: 779,
 806: 780,
 807: 781,
 808: 782,
 809: 783,
 810: 784,
 811: 785,
 812: 786,
 813: 787,
 814: 788,
 815: 789,
 816: 790,
 817: 791,
 819: 792,
 820: 793,
 821: 794,
 822: 795,
 823: 796,
 824: 797,
 825: 798,
 826: 799,
 827: 800,
 828: 801,
 829: 802,
 830: 803,
 831: 804,
 832: 805,
 833: 806,
 834: 807,
 835: 808,
 836: 809,
 837: 810,
 838: 811,
 839: 812,
 840: 813,
 841: 814,
 842: 815,
 844: 816,
 845: 817,
 846: 818,
 847: 819,
 848: 820,
 849: 821,
 850: 822,
 851: 823,
 852: 824,
 853: 825,
 854: 826,
 855: 827,
 856: 828,
 857: 829,
 858: 830,
 859: 831,
 860: 832,
 861: 833,
 862: 834,
 863: 835,
 864: 836,
 865: 837,
 866: 838,
 867: 839,
 868: 840,
 869: 841,
 870: 842,
 871: 843,
 872: 844,
 873: 845,
 874: 846,
 875: 847,
 876: 848,
 877: 849,
 878: 850,
 879: 851,
 880: 852,
 881: 853,
 882: 854,
 883: 855,
 884: 856,
 885: 857,
 886: 858,
 887: 859,
 888: 860,
 889: 861,
 890: 862,
 891: 863,
 892: 864,
 893: 865,
 894: 866,
 895: 867,
 896: 868,
 897: 869,
 898: 870,
 899: 871,
 900: 872,
 901: 873,
 902: 874,
 903: 875,
 904: 876,
 905: 877,
 906: 878,
 907: 879,
 908: 880,
 909: 881,
 910: 882,
 911: 883,
 912: 884,
 914: 885,
 916: 886,
 917: 887,
 918: 888,
 919: 889,
 920: 890,
 921: 891,
 922: 892,
 923: 893,
 924: 894,
 925: 895,
 926: 896,
 927: 897,
 928: 898,
 929: 899,
 930: 900,
 931: 901,
 932: 902,
 933: 903,
 934: 904,
 935: 905,
 936: 906,
 937: 907,
 938: 908,
 939: 909,
 940: 910,
 941: 911,
 942: 912,
 943: 913,
 944: 914,
 945: 915,
 946: 916,
 947: 917,
 948: 918,
 949: 919,
 950: 920,
 951: 921,
 952: 922,
 953: 923,
 954: 924,
 955: 925,
 956: 926,
 957: 927,
 959: 928,
 960: 929,
 961: 930,
 962: 931,
 964: 932,
 965: 933,
 967: 934,
 968: 935,
 969: 936,
 970: 937,
 971: 938,
 972: 939,
 973: 940,
 974: 941,
 975: 942,
 978: 943,
 979: 944,
 980: 945,
 981: 946,
 982: 947,
 983: 948,
 984: 949,
 985: 950,
 987: 951,
 988: 952,
 989: 953,
 990: 954,
 991: 955,
 993: 956,
 994: 957,
 995: 958,
 996: 959,
 997: 960,
 998: 961,
 999: 962,
 1000: 963,
 1001: 964,
 1002: 965,
 1003: 966,
 1004: 967,
 1005: 968,
 1006: 969,
 1007: 970,
 1008: 971,
 1009: 972,
 1010: 973,
 1011: 974,
 1014: 975,
 1015: 976,
 1016: 977,
 1017: 978,
 1018: 979,
 1019: 980,
 1020: 981,
 1021: 982,
 1022: 983,
 1023: 984,
 1024: 985,
 1025: 986,
 1026: 987,
 1027: 988,
 1028: 989,
 1029: 990,
 1030: 991,
 1031: 992,
 1032: 993,
 1033: 994,
 1034: 995,
 1035: 996,
 1036: 997,
 1037: 998,
 1038: 999,
 ...}

# cf with svd++ from surprise

In [12]:
books

,id,book_id,title,authors,decade_year
0,1,2767052,"The Hunger Games (The Hunger Games, #1)",author_suzanne_collins,decade_2000s
1,2,3,Harry Potter and the Sorcerer's Stone (Harry P...,author_jk_rowling author_mary_grandpr,decade_1990s
2,3,41865,"Twilight (Twilight, #1)",author_stephenie_meyer,decade_2000s
3,4,2657,To Kill a Mockingbird,author_harper_lee,decade_1960s
4,5,4671,The Great Gatsby,author_f_scott_fitzgerald,decade_1920s
...,...,...,...,...,...
9994,9995,15613,"Billy Budd, Sailor",author_herman_melville,decade_1920s
9995,9996,7130616,"Bayou Moon (The Edge, #2)",author_ilona_andrews,decade_2010s
9996,9997,208324,"Means of Ascent (The Years of Lyndon Johnson, #2)",author_robert_a_caro,decade_1990s
9997,9998,77431,The Mauritius Command,author_patrick_obrian,decade_1970s
9998,9999,8565083,Cinderella Ate My Daughter: Dispatches from th...,author_peggy_orenstein,decade_2010s

In [13]:
books.drop(columns=['book_id'], inplace=True)
books.rename(columns={'id': 'book_id'}, inplace=True)
books.tail()

,book_id,title,authors,decade_year
9994,9995,"Billy Budd, Sailor",author_herman_melville,decade_1920s
9995,9996,"Bayou Moon (The Edge, #2)",author_ilona_andrews,decade_2010s
9996,9997,"Means of Ascent (The Years of Lyndon Johnson, #2)",author_robert_a_caro,decade_1990s
9997,9998,The Mauritius Command,author_patrick_obrian,decade_1970s
9998,9999,Cinderella Ate My Daughter: Dispatches from th...,author_peggy_orenstein,decade_2010s

In [14]:
ratings

        book_id  user_id  rating
0             1      314       5
1             1      439       3
2             1      588       5
3             1     1169       4
4             1     1185       4
...         ...      ...     ...
981751    10000    48386       5
981752    10000    49007       4
981753    10000    49383       5
981754    10000    50124       5
981755    10000    51328       1

[981756 rows x 3 columns]

In [15]:
# Filter to only book_ids present in the books metadata file
valid_ids        = set(books['book_id'].unique()) if 'book_id' in books.columns else set(books['book_id'].unique())
ratings_filtered = ratings[ratings['book_id'].isin(valid_ids)].copy()

In [16]:
len(valid_ids)

8730

In [17]:
ratings_filtered['book_id'].nunique()

8730

In [18]:
# Build Surprise dataset
reader   = Reader(rating_scale=(1, 5))
data     = Dataset.load_from_df(ratings_filtered[['user_id', 'book_id', 'rating']], reader)
trainset, testset = surprise_split(data, test_size=0.2, random_state=42)

In [19]:
reader

In [20]:
data

In [21]:
trainset

In [22]:
testset

[(14001, 5306, 4.0),
 (40226, 7111, 4.0),
 (38300, 4012, 3.0),
 (34189, 2509, 3.0),
 (49505, 7834, 5.0),
 (50976, 404, 4.0),
 (9135, 6650, 3.0),
 (29282, 4625, 5.0),
 (24461, 6592, 5.0),
 (5569, 5101, 5.0),
 (15687, 805, 3.0),
 (37944, 8561, 5.0),
 (41495, 1049, 5.0),
 (21954, 8572, 4.0),
 (6430, 9666, 3.0),
 (8209, 3715, 2.0),
 (52051, 7285, 5.0),
 (11837, 442, 3.0),
 (4900, 1052, 3.0),
 (11957, 9877, 5.0),
 (23767, 7591, 4.0),
 (8958, 7747, 5.0),
 (15157, 2732, 3.0),
 (17144, 4727, 5.0),
 (39213, 4148, 4.0),
 (47232, 6486, 5.0),
 (18077, 2329, 4.0),
 (11325, 3958, 5.0),
 (10231, 1965, 5.0),
 (6016, 1630, 3.0),
 (39177, 3852, 4.0),
 (24437, 4850, 5.0),
 (49050, 5624, 3.0),
 (31537, 8314, 5.0),
 (10297, 167, 5.0),
 (19484, 334, 3.0),
 (7064, 5048, 4.0),
 (3521, 6488, 4.0),
 (22384, 4519, 2.0),
 (4715, 259, 3.0),
 (30554, 7265, 3.0),
 (15567, 3767, 2.0),
 (36516, 3024, 5.0),
 (4383, 4905, 2.0),
 (19729, 808, 4.0),
 (27687, 8250, 3.0),
 (41888, 5732, 5.0),
 (5629, 1954, 3.0),
 (13544, 2831, 5.0),
 (36689, 5581, 4.0),
 (13693, 1271, 5.0),
 (30875, 6759, 4.0),
 (51919, 1056, 4.0),
 (39515, 6356, 3.0),
 (34146, 7138, 5.0),
 (30729, 7662, 3.0),
 (21986, 3641, 4.0),
 (1782, 6125, 5.0),
 (9357, 362, 5.0),
 (43321, 3537, 2.0),
 (19600, 9422, 4.0),
 (12441, 5533, 3.0),
 (49885, 7597, 3.0),
 (40927, 7724, 3.0),
 (7749, 9511, 3.0),
 (1440, 3907, 3.0),
 (42071, 7192, 5.0),
 (41926, 2523, 5.0),
 (39508, 692, 4.0),
 (10509, 924, 5.0),
 (50054, 3146, 3.0),
 (30476, 3024, 4.0),
 (4121, 5961, 4.0),
 (7443, 8066, 5.0),
 (5461, 1161, 4.0),
 (9733, 852, 3.0),
 (9678, 6538, 3.0),
 (12840, 4508, 4.0),
 (50013, 9479, 5.0),
 (37463, 7250, 4.0),
 (20241, 1099, 5.0),
 (15998, 2469, 2.0),
 (25041, 4456, 3.0),
 (36240, 2306, 4.0),
 (25642, 9181, 3.0),
 (28824, 699, 3.0),
 (30208, 6473, 2.0),
 (27459, 1541, 5.0),
 (8808, 8902, 4.0),
 (21316, 1211, 5.0),
 (48855, 1183, 4.0),
 (23681, 7489, 4.0),
 (17228, 3938, 4.0),
 (23311, 5374, 5.0),
 (6846, 7379, 4.0),
 (2958, 921, 4.0),
 (35326, 1204, 3.0),
 (21725, 4360, 2.0),
 (5656, 1841, 3.0),
 (11727, 2346, 4.0),
 (44987, 9358, 5.0),
 (31336, 784, 4.0),
 (20075, 5223, 5.0),
 (44197, 4894, 4.0),
 (43082, 9178, 4.0),
 (23650, 2983, 5.0),
 (19248, 1437, 3.0),
 (12022, 7480, 5.0),
 (15670, 6818, 2.0),
 (46926, 5907, 3.0),
 (12923, 6287, 4.0),
 (28654, 9045, 4.0),
 (49832, 4749, 4.0),
 (20918, 6556, 3.0),
 (19680, 6310, 3.0),
 (20521, 8101, 4.0),
 (10580, 2157, 4.0),
 (41249, 1881, 5.0),
 (1175, 2148, 2.0),
 (200, 5762, 4.0),
 (12186, 2736, 3.0),
 (4922, 8487, 5.0),
 (13739, 2120, 4.0),
 (51762, 1199, 5.0),
 (23839, 1063, 4.0),
 (8483, 4016, 3.0),
 (16596, 9456, 5.0),
 (7028, 4528, 4.0),
 (8179, 4472, 4.0),
 (14188, 7665, 3.0),
 (15129, 8608, 4.0),
 (38173, 1554, 4.0),
 (6943, 6715, 3.0),
 (44937, 6769, 2.0),
 (2434, 5667, 3.0),
 (8278, 481, 3.0),
 (21058, 3295, 5.0),
 (23440, 7522, 3.0),
 (17404, 392, 2.0),
 (44471, 1506, 1.0),
 (969, 1703, 3.0),
 (27818, 5834, 3.0),
 (33836, 4984, 4.0),
 (6056, 2980, 4.0),
 (50205, 5600, 1.0),
 (8823, 3912, 3.0),
 (45803, 3893, 5.0),
 (30159, 5053, 5.0),
 (33599, 4234, 5.0),
 (36984, 2368, 3.0),
 (46295, 4201, 5.0),
 (6876, 6319, 2.0),
 (8213, 4568, 5.0),
 (36839, 9092, 4.0),
 (46692, 6282, 3.0),
 (23497, 1430, 4.0),
 (850, 7008, 5.0),
 (5042, 1134, 5.0),
 (23839, 244, 3.0),
 (23872, 6172, 4.0),
 (35052, 5506, 5.0),
 (21166, 3133, 5.0),
 (14865, 3092, 4.0),
 (3463, 5922, 5.0),
 (29143, 4039, 2.0),
 (26898, 828, 5.0),
 (3119, 5447, 3.0),
 (25925, 3872, 3.0),
 (1027, 6354, 4.0),
 (1113, 5663, 3.0),
 (51194, 8949, 4.0),
 (46818, 1286, 5.0),
 (22201, 3193, 4.0),
 (537, 9981, 4.0),
 (4089, 6041, 3.0),
 (48482, 27, 4.0),
 (42144, 6504, 4.0),
 (29574, 3642, 5.0),
 (10885, 516, 5.0),
 (52915, 7657, 5.0),
 (42623, 5556, 5.0),
 (3349, 7564, 3.0),
 (18995, 1440, 4.0),
 (12728, 1270, 3.0),
 (44199, 3270, 3.0),
 (47946, 9523, 2.0),
 (48089, 3652, 3.0),
 (48285, 336, 4.0),
 (50851, 2112, 2.0),
 (24237, 6774, 5.0),
 (23966, 8982, 3.0),
 (52731, 3672, 4.0),
 (4773, 2357, 4.0),
 (50371, 9446, 3.0),
 (29947, 3810, 3.0),
 (47232, 7065, 5.0),
 (7580, 1772, 5.0),
 (29000, 1086, 4.0),
 (11945, 140, 5.0),
 (11691, 3764, 4.0),
 (10610, 3933, 5.0),
 (51088, 8106, 4.0),
 (48007, 602, 2.0),
 (35393, 1042, 3.0),
 (49998, 6815, 3.0),
 (29151, 5979, 5.0),
 (3817, 7833, 5.0),
 (32357, 3349, 4.0),
 (49972, 6884, 4.0),
 (41988, 3688, 3.0),
 (39337, 6024, 5.0),
 (39172, 6557, 5.0),
 (43105, 3887, 5.0),
 (5144, 8591, 5.0),
 (6856, 603, 5.0),
 (18550, 110, 5.0),
 (14056, 1494, 5.0),
 (32201, 1553, 5.0),
 (16875, 9425, 4.0),
 (47078, 2975, 4.0),
 (25484, 2797, 5.0),
 (50693, 9293, 4.0),
 (48107, 3405, 4.0),
 (1583, 3535, 5.0),
 (45855, 4791, 3.0),
 (21079, 6497, 5.0),
 (45935, 1138, 3.0),
 (21761, 1862, 5.0),
 (38597, 3136, 4.0),
 (25540, 7655, 5.0),
 (43744, 6390, 5.0),
 (52663, 8923, 4.0),
 (49150, 3872, 5.0),
 (24324, 6429, 4.0),
 (38845, 4739, 4.0),
 (28187, 3949, 3.0),
 (26245, 7456, 4.0),
 (25443, 4542, 3.0),
 (43251, 7430, 4.0),
 (42839, 7136, 4.0),
 (17257, 9189, 5.0),
 (6315, 1460, 3.0),
 (17522, 1988, 3.0),
 (22776, 632, 3.0),
 (13073, 709, 4.0),
 (5885, 4227, 3.0),
 (33679, 1394, 5.0),
 (9843, 3994, 5.0),
 (39508, 303, 5.0),
 (30396, 3801, 5.0),
 (41988, 1596, 2.0),
 (17242, 1605, 4.0),
 (25472, 1064, 4.0),
 (30716, 9413, 5.0),
 (34688, 305, 3.0),
 (9587, 777, 4.0),
 (35504, 3531, 5.0),
 (7205, 3753, 5.0),
 (10885, 534, 3.0),
 (21487, 705, 3.0),
 (30100, 4204, 4.0),
 (48966, 5600, 3.0),
 (48218, 1729, 2.0),
 (16973, 3371, 3.0),
 (40763, 2151, 5.0),
 (21922, 8312, 5.0),
 (44617, 846, 4.0),
 (21024, 3071, 3.0),
 (13596, 9622, 3.0),
 (40490, 53, 5.0),
 (52095, 4353, 4.0),
 (6068, 7285, 5.0),
 (36259, 1724, 2.0),
 (53295, 4295, 4.0),
 (50689, 6965, 5.0),
 (44927, 7304, 3.0),
 (12161, 9586, 4.0),
 (14114, 1805, 2.0),
 (38851, 135, 3.0),
 (17924, 4651, 4.0),
 (5668, 6501, 4.0),
 (5764, 3076, 4.0),
 (22447, 6397, 3.0),
 (39731, 8620, 5.0),
 (12156, 890, 5.0),
 (26108, 3156, 2.0),
 (38240, 5286, 4.0),
 (7801, 1236, 4.0),
 (38847, 611, 2.0),
 (14599, 3514, 4.0),
 (11360, 7574, 4.0),
 (29671, 760, 5.0),
 (2334, 3006, 5.0),
 (1057, 2129, 4.0),
 (16496, 5650, 3.0),
 (47478, 561, 2.0),
 (21447, 5458, 5.0),
 (43519, 6155, 5.0),
 (42943, 660, 3.0),
 (4916, 3430, 4.0),
 (995, 6620, 2.0),
 (19356, 2924, 3.0),
 (363, 2522, 2.0),
 (3829, 1417, 1.0),
 (39215, 2890, 5.0),
 (16958, 2040, 5.0),
 (43958, 9151, 5.0),
 (4383, 6816, 3.0),
 (33793, 4995, 3.0),
 (16663, 1212, 5.0),
 (2959, 2780, 4.0),
 (463, 3635, 4.0),
 (6630, 3065, 2.0),
 (26723, 4859, 5.0),
 (1794, 64, 5.0),
 (51845, 2904, 2.0),
 (29516, 7988, 2.0),
 (50582, 6155, 3.0),
 (22084, 2593, 4.0),
 (26656, 8228, 5.0),
 (27245, 3074, 5.0),
 (4821, 458, 2.0),
 (53348, 3135, 5.0),
 (11363, 3481, 1.0),
 (49749, 1078, 5.0),
 (13106, 9795, 3.0),
 (23637, 7346, 4.0),
 (28025, 2217, 5.0),
 (19998, 7711, 3.0),
 (17937, 4375, 5.0),
 (41953, 4373, 4.0),
 (10249, 586, 3.0),
 (46554, 8970, 4.0),
 (32669, 7928, 4.0),
 (519, 4137, 3.0),
 (16549, 3380, 4.0),
 (16874, 7758, 4.0),
 (346, 4873, 5.0),
 (45924, 8754, 4.0),
 (49139, 4971, 4.0),
 (21584, 5872, 5.0),
 (5102, 5012, 5.0),
 (33227, 6379, 4.0),
 (3170, 7400, 4.0),
 (38997, 7965, 4.0),
 (50905, 1329, 4.0),
 (40430, 2798, 5.0),
 (47773, 4373, 5.0),
 (38845, 6890, 2.0),
 (50519, 5118, 4.0),
 (43890, 5153, 4.0),
 (38102, 8423, 4.0),
 (22154, 1581, 3.0),
 (41337, 2602, 4.0),
 (24389, 97, 4.0),
 (3022, 485, 1.0),
 (18670, 4598, 4.0),
 (24862, 9394, 5.0),
 (48137, 3627, 5.0),
 (11417, 3389, 1.0),
 (4422, 7908, 3.0),
 (41204, 672, 4.0),
 (9234, 6248, 3.0),
 (8764, 5231, 4.0),
 (29366, 3292, 5.0),
 (28305, 3683, 4.0),
 (31741, 3954, 3.0),
 (1185, 200, 3.0),
 (7712, 6443, 4.0),
 (25266, 5781, 4.0),
 (28022, 8924, 2.0),
 (9705, 8335, 2.0),
 (25890, 2545, 5.0),
 (27027, 704, 5.0),
 (47411, 715, 3.0),
 (35431, 6897, 1.0),
 (153, 9917, 3.0),
 (35149, 9975, 4.0),
 (49612, 3811, 5.0),
 (30070, 7799, 5.0),
 (24388, 4881, 5.0),
 (29581, 3850, 3.0),
 (31327, 8603, 3.0),
 (44121, 1691, 4.0),
 (3298, 9175, 2.0),
 (13113, 8070, 5.0),
 (20755, 9187, 3.0),
 (2386, 9229, 3.0),
 (26990, 3047, 4.0),
 (51399, 2855, 5.0),
 (35730, 4807, 4.0),
 (17691, 2238, 4.0),
 (12874, 251, 4.0),
 (13886, 5474, 3.0),
 (38002, 5354, 5.0),
 (42200, 1572, 4.0),
 (38424, 3384, 5.0),
 (9590, 443, 3.0),
 (51618, 141, 5.0),
 (21827, 7669, 5.0),
 (45329, 8798, 2.0),
 (33945, 1473, 5.0),
 (52214, 947, 2.0),
 (13103, 9651, 4.0),
 (6064, 1740, 3.0),
 (53131, 4349, 4.0),
 (45493, 1953, 2.0),
 (43520, 5216, 4.0),
 (34763, 3058, 3.0),
 (5568, 5951, 5.0),
 (32214, 9411, 5.0),
 (36415, 4246, 5.0),
 (2626, 9715, 2.0),
 (19351, 4243, 3.0),
 (26214, 6248, 3.0),
 (19335, 2366, 3.0),
 (24663, 8364, 5.0),
 (8265, 8175, 3.0),
 (16779, 3461, 4.0),
 (46133, 4193, 4.0),
 (18120, 969, 2.0),
 (43455, 8302, 3.0),
 (9020, 7593, 5.0),
 (42223, 6277, 4.0),
 (3796, 616, 4.0),
 (14637, 5542, 5.0),
 (18812, 2962, 2.0),
 (45437, 7834, 4.0),
 (1388, 3951, 5.0),
 (52514, 4675, 3.0),
 (5912, 1399, 5.0),
 (52250, 9077, 4.0),
 (43985, 1739, 4.0),
 (29225, 5687, 3.0),
 (51345, 4984, 5.0),
 (40008, 4562, 4.0),
 (44333, 6231, 4.0),
 (3022, 2090, 3.0),
 (35578, 2942, 5.0),
 (24190, 8938, 5.0),
 (29689, 55, 4.0),
 (12957, 2725, 3.0),
 (21803, 6519, 5.0),
 (28310, 2616, 3.0),
 (26260, 1737, 4.0),
 (8249, 1652, 5.0),
 (6008, 7047, 3.0),
 (24092, 1696, 4.0),
 (40961, 1172, 5.0),
 (25676, 1726, 4.0),
 (52094, 7444, 5.0),
 (52211, 6886, 3.0),
 (25289, 4758, 5.0),
 (4302, 6174, 4.0),
 (22238, 3131, 3.0),
 (4017, 5684, 3.0),
 (12226, 4350, 4.0),
 (49251, 1963, 5.0),
 (2589, 8931, 3.0),
 (42667, 4567, 4.0),
 (11628, 6173, 2.0),
 (2173, 1746, 3.0),
 (16904, 3487, 4.0),
 (42389, 4585, 5.0),
 (22527, 6410, 1.0),
 (9007, 5254, 5.0),
 (41489, 4500, 2.0),
 (11233, 849, 1.0),
 (44508, 875, 1.0),
 (456, 4147, 4.0),
 (23722, 1214, 1.0),
 (15228, 3030, 5.0),
 (31869, 9130, 3.0),
 (13694, 3713, 3.0),
 (1533, 8517, 4.0),
 (22202, 3468, 5.0),
 (18363, 1851, 3.0),
 (19879, 6361, 5.0),
 (15453, 6647, 3.0),
 (14538, 7800, 1.0),
 (39693, 1698, 4.0),
 (35831, 5928, 3.0),
 (13809, 8305, 4.0),
 (33872, 616, 5.0),
 (50098, 6452, 3.0),
 (247, 5216, 4.0),
 (43185, 2233, 5.0),
 (30313, 16, 5.0),
 (14023, 6551, 4.0),
 (48280, 9213, 4.0),
 (10944, 930, 3.0),
 (39237, 5270, 2.0),
 (3935, 6829, 5.0),
 (30035, 7436, 4.0),
 (10120, 5179, 2.0),
 (35866, 700, 3.0),
 (15767, 522, 4.0),
 (4133, 3151, 5.0),
 (40993, 1072, 5.0),
 (34763, 2306, 4.0),
 (15561, 3903, 4.0),
 (381, 5515, 5.0),
 (52740, 262, 5.0),
 (43037, 574, 5.0),
 (6132, 8860, 5.0),
 (24017, 4198, 4.0),
 (10592, 5044, 5.0),
 (12395, 933, 5.0),
 (21913, 9897, 4.0),
 (26204, 1263, 4.0),
 (6200, 8094, 5.0),
 (735, 5932, 4.0),
 (46199, 3203, 5.0),
 (26363, 1559, 3.0),
 (3022, 2937, 4.0),
 (4030, 9830, 3.0),
 (1441, 9032, 3.0),
 (3005, 136, 5.0),
 (30602, 5993, 5.0),
 (2553, 290, 5.0),
 (26430, 3754, 4.0),
 (33357, 3686, 4.0),
 (8407, 706, 5.0),
 (2823, 5615, 2.0),
 (43756, 1017, 3.0),
 (23114, 2073, 1.0),
 (9971, 2965, 5.0),
 (35443, 6349, 5.0),
 (48196, 215, 5.0),
 (43976, 3977, 4.0),
 (25915, 6518, 4.0),
 (15741, 7313, 5.0),
 (13314, 9040, 5.0),
 (34062, 3778, 5.0),
 (28032, 539, 2.0),
 (50158, 4137, 4.0),
 (4038, 6174, 4.0),
 (15082, 860, 5.0),
 (9610, 4395, 5.0),
 (51271, 1685, 5.0),
 (17804, 2479, 3.0),
 (15243, 7065, 4.0),
 (26696, 9311, 4.0),
 (33764, 2016, 4.0),
 (732, 6036, 3.0),
 (41517, 6787, 4.0),
 (48057, 3879, 4.0),
 (38756, 3654, 5.0),
 (18361, 1892, 4.0),
 (29472, 6272, 3.0),
 (6252, 2013, 3.0),
 (12002, 2674, 3.0),
 (767, 1839, 2.0),
 (28754, 5154, 4.0),
 (50529, 4599, 3.0),
 (9285, 3470, 5.0),
 (29997, 7184, 4.0),
 (4606, 510, 5.0),
 (11836, 223, 3.0),
 (10394, 8218, 3.0),
 (49103, 448, 1.0),
 (20701, 4350, 4.0),
 (36725, 7095, 4.0),
 (17013, 585, 3.0),
 (48519, 8142, 2.0),
 (16956, 5886, 4.0),
 (13658, 4698, 4.0),
 (11056, 3608, 1.0),
 (8805, 2621, 4.0),
 (38275, 3075, 2.0),
 (32649, 737, 4.0),
 (51151, 1484, 4.0),
 (9483, 3792, 5.0),
 (23603, 7534, 5.0),
 (25344, 8318, 3.0),
 (46479, 5684, 2.0),
 (12185, 3918, 3.0),
 (33454, 2331, 5.0),
 (44771, 4588, 3.0),
 (12808, 4859, 3.0),
 (7847, 7064, 4.0),
 (30290, 627, 5.0),
 (4382, 5472, 4.0),
 (39709, 2293, 5.0),
 (45604, 2093, 5.0),
 (23309, 2889, 4.0),
 (20572, 3806, 3.0),
 (13876, 2282, 5.0),
 (13544, 3156, 5.0),
 (27035, 3458, 4.0),
 (2288, 1265, 4.0),
 (12390, 4856, 5.0),
 (9123, 1634, 4.0),
 (2743, 5525, 2.0),
 (35126, 9380, 5.0),
 (41628, 9336, 3.0),
 (33856, 4948, 5.0),
 (45956, 9169, 4.0),
 (25437, 3460, 5.0),
 (29040, 7906, 4.0),
 (19900, 6283, 4.0),
 (28192, 8081, 5.0),
 (18090, 1308, 5.0),
 (35259, 2644, 3.0),
 (14603, 899, 4.0),
 (23138, 3496, 5.0),
 (49211, 5974, 3.0),
 (45554, 780, 5.0),
 (24686, 2519, 5.0),
 (8738, 5733, 4.0),
 (36387, 7729, 3.0),
 (4816, 362, 2.0),
 (23799, 4182, 5.0),
 (3278, 8269, 3.0),
 (48762, 7493, 3.0),
 (12160, 9414, 5.0),
 (28657, 4617, 3.0),
 (22161, 5115, 5.0),
 (16022, 5615, 3.0),
 (46490, 8056, 4.0),
 (26497, 9448, 5.0),
 (29655, 8668, 4.0),
 (11745, 8444, 4.0),
 (40849, 3901, 3.0),
 (50500, 2195, 4.0),
 (29074, 4175, 4.0),
 (38665, 7414, 4.0),
 (6968, 8739, 2.0),
 (36240, 534, 4.0),
 (7648, 6797, 5.0),
 (19729, 200, 4.0),
 (15318, 364, 4.0),
 (16042, 3610, 3.0),
 (40430, 3916, 4.0),
 (16177, 2209, 5.0),
 (2910, 2920, 4.0),
 (20379, 3214, 5.0),
 (20655, 8818, 3.0),
 (36240, 306, 4.0),
 (30192, 9062, 5.0),
 (15889, 129, 4.0),
 (14742, 1332, 4.0),
 (12851, 1531, 5.0),
 (992, 8035, 5.0),
 (14582, 3837, 4.0),
 (446, 5748, 3.0),
 (11877, 1760, 5.0),
 (39974, 1773, 5.0),
 (725, 1001, 3.0),
 (11221, 6684, 4.0),
 (27722, 2666, 3.0),
 (13297, 4007, 5.0),
 (37834, 199, 4.0),
 (39539, 9778, 4.0),
 (39043, 7975, 4.0),
 (22168, 2499, 3.0),
 (46378, 7347, 5.0),
 (38874, 4222, 4.0),
 (3045, 8427, 3.0),
 (10123, 6609, 3.0),
 (11955, 9915, 4.0),
 (20592, 4094, 5.0),
 (19731, 3229, 3.0),
 (46916, 4221, 4.0),
 (44712, 7312, 5.0),
 (48440, 200, 4.0),
 (11810, 2367, 4.0),
 (10953, 1518, 4.0),
 (1964, 9747, 4.0),
 (31074, 4273, 4.0),
 (39265, 9508, 5.0),
 (34679, 7907, 4.0),
 (9285, 163, 4.0),
 (3305, 7047, 3.0),
 (11292, 7715, 5.0),
 (39655, 630, 3.0),
 (38509, 1960, 4.0),
 (50873, 4970, 4.0),
 (26363, 3161, 4.0),
 (48617, 5356, 5.0),
 (6966, 4220, 4.0),
 (16639, 4062, 5.0),
 (1845, 6192, 4.0),
 (21487, 364, 5.0),
 (23458, 708, 2.0),
 (30704, 9360, 5.0),
 (41859, 9394, 4.0),
 (35549, 5571, 3.0),
 (23175, 2639, 4.0),
 (51820, 8076, 5.0),
 (42404, 111, 4.0),
 (35045, 4256, 5.0),
 (15505, 6324, 2.0),
 (20678, 5634, 3.0),
 (21315, 2496, 1.0),
 (33326, 1323, 4.0),
 (48291, 1742, 3.0),
 (24702, 9383, 5.0),
 (38286, 2568, 2.0),
 (38512, 3035, 3.0),
 (50329, 7921, 4.0),
 (22202, 1910, 5.0),
 (15370, 6158, 4.0),
 (1359, 5641, 3.0),
 (53407, 4045, 3.0),
 (53057, 1951, 4.0),
 (7743, 4400, 3.0),
 (12838, 1538, 4.0),
 (26983, 791, 5.0),
 (39398, 9500, 5.0),
 (6648, 4323, 4.0),
 (13469, 7676, 5.0),
 (39216, 8958, 4.0),
 (19253, 7566, 5.0),
 (31100, 6161, 4.0),
 (13274, 879, 4.0),
 (21842, 7960, 3.0),
 (6929, 1264, 5.0),
 (33068, 5300, 3.0),
 (33947, 6395, 5.0),
 (40383, 4452, 4.0),
 (10638, 2433, 4.0),
 (1758, 4336, 5.0),
 (3314, 1266, 3.0),
 (34585, 6066, 5.0),
 (18920, 576, 3.0),
 (29627, 1237, 3.0),
 (424, 850, 3.0),
 (51652, 1819, 5.0),
 (3674, 3489, 5.0),
 (49636, 351, 5.0),
 (2336, 3685, 3.0),
 (29871, 3359, 3.0),
 (34623, 8383, 5.0),
 (47545, 7792, 5.0),
 (32809, 5972, 4.0),
 (34896, 6802, 4.0),
 (7997, 8964, 4.0),
 (28496, 9046, 5.0),
 (19612, 2241, 4.0),
 (6195, 4766, 4.0),
 (44952, 7238, 5.0),
 (10060, 4789, 4.0),
 (38146, 1134, 4.0),
 (32099, 6982, 5.0),
 (34915, 3232, 5.0),
 (42886, 4744, 4.0),
 (22319, 3892, 4.0),
 (51412, 7334, 3.0),
 (18100, 386, 5.0),
 (42508, 2648, 5.0),
 (52852, 5116, 3.0),
 (10502, 3304, 4.0),
 (23334, 9476, 3.0),
 (24812, 4359, 5.0),
 (19892, 2069, 4.0),
 (25606, 4558, 4.0),
 (45269, 428, 3.0),
 (47034, 9101, 3.0),
 (35824, 4932, 5.0),
 (18989, 6608, 2.0),
 (41230, 400, 4.0),
 (53078, 2333, 4.0),
 (12667, 6395, 5.0),
 (13580, 2704, 4.0),
 (48766, 5921, 5.0),
 (8623, 3429, 3.0),
 (45888, 4894, 2.0),
 (15290, 6940, 3.0),
 (23768, 312, 4.0),
 (11997, 4460, 3.0),
 (49543, 9713, 3.0),
 (51762, 2451, 4.0),
 (16917, 8930, 4.0),
 (30960, 8369, 2.0),
 (15299, 1735, 5.0),
 (21380, 2763, 4.0),
 (52214, 1470, 2.0),
 (51814, 5289, 5.0),
 (12090, 6547, 5.0),
 (5461, 93, 5.0),
 (2337, 3774, 4.0),
 (20967, 57, 5.0),
 (33783, 8818, 4.0),
 (10129, 9811, 4.0),
 (20792, 4416, 4.0),
 (9557, 8161, 4.0),
 (13426, 1840, 4.0),
 (33983, 2160, 4.0),
 (39370, 5597, 5.0),
 (35618, 3254, 5.0),
 (49514, 545, 3.0),
 (17928, 1351, 3.0),
 (45888, 3794, 4.0),
 (4795, 499, 5.0),
 (47988, 4418, 4.0),
 (16824, 9536, 3.0),
 (13003, 5365, 4.0),
 (34001, 9428, 4.0),
 (51581, 2774, 5.0),
 (28532, 3249, 4.0),
 (6705, 8383, 3.0),
 (33053, 2641, 3.0),
 (42397, 4997, 5.0),
 (47249, 1343, 4.0),
 (9360, 1064, 5.0),
 (53077, 4741, 4.0),
 (32305, 1566, 2.0),
 (12661, 3165, 3.0),
 (34594, 3853, 4.0),
 (35762, 5686, 3.0),
 (24619, 7819, 5.0),
 (3436, 4561, 2.0),
 (6660, 2190, 3.0),
 (27940, 2547, 4.0),
 (53173, 2971, 4.0),
 (36633, 4175, 3.0),
 (6647, 5120, 5.0),
 (41616, 1255, 5.0),
 (50801, 2901, 3.0),
 (51708, 5181, 5.0),
 (38792, 7644, 4.0),
 (1189, 8817, 4.0),
 (20332, 282, 5.0),
 (4842, 5087, 3.0),
 (24102, 3846, 2.0),
 (46507, 3749, 5.0),
 (23321, 8428, 5.0),
 (39437, 7851, 4.0),
 (43137, 1966, 4.0),
 (4859, 3904, 3.0),
 (25692, 2627, 4.0),
 (17984, 1388, 4.0),
 (5928, 7985, 5.0),
 (26930, 6910, 4.0),
 (15745, 3879, 4.0),
 (9815, 6743, 4.0),
 (13776, 1434, 4.0),
 (23170, 5355, 3.0),
 (43337, 5017, 5.0),
 (47508, 2768, 5.0),
 (51831, 8352, 3.0),
 (42793, 8188, 4.0),
 (31327, 676, 2.0),
 (21164, 1266, 5.0),
 (12128, 8535, 4.0),
 (18106, 9753, 4.0),
 (39788, 5363, 3.0),
 (2341, 6215, 2.0),
 (16094, 1636, 4.0),
 (10094, 5721, 3.0),
 (51460, 919, 3.0),
 (30601, 656, 2.0),
 (37690, 894, 4.0),
 (22099, 7048, 4.0),
 (45414, 7078, 3.0),
 (18743, 9489, 5.0),
 (23603, 3456, 5.0),
 (37686, 3526, 4.0),
 (6462, 7425, 3.0),
 (4954, 3149, 1.0),
 (21592, 9774, 5.0),
 (4096, 1350, 5.0),
 (33341, 5828, 5.0),
 (2967, 3987, 3.0),
 (40313, 3928, 4.0),
 (3935, 7755, 2.0),
 (41714, 9892, 3.0),
 (53366, 2951, 4.0),
 (25130, 1777, 3.0),
 (10227, 7327, 4.0),
 (38231, 8744, 3.0),
 (27455, 568, 5.0),
 (17056, 6306, 4.0),
 (43676, 5615, 4.0),
 (1812, 6125, 4.0),
 (49026, 1416, 3.0),
 (24748, 3319, 3.0),
 (17883, 820, 4.0),
 (6093, 6962, 2.0),
 (38864, 6356, 4.0),
 (22195, 5399, 4.0),
 (5273, 9395, 5.0),
 (12848, 4320, 4.0),
 (49022, 1353, 5.0),
 (28959, 6982, 5.0),
 (40427, 8962, 4.0),
 (33665, 6187, 5.0),
 (1686, 7738, 4.0),
 (19600, 8885, 3.0),
 (41883, 9578, 5.0),
 (28458, 6632, 3.0),
 (52612, 6200, 4.0),
 (15940, 6827, 4.0),
 (39973, 6869, 4.0),
 (16425, 4362, 4.0),
 (52334, 1917, 5.0),
 (45073, 6356, 4.0),
 (6025, 638, 3.0),
 (11801, 8910, 4.0),
 (646, 5140, 4.0),
 (26635, 9282, 5.0),
 (12643, 9422, 4.0),
 (42769, 7225, 3.0),
 (53077, 2106, 4.0),
 (53071, 4312, 4.0),
 (6463, 3555, 3.0),
 (27770, 4629, 1.0),
 (8239, 4127, 5.0),
 (28438, 3777, 5.0),
 (37490, 5956, 4.0),
 (51762, 77, 5.0),
 (30959, 6003, 5.0),
 (47960, 2151, 3.0),
 (6226, 8875, 5.0),
 (20183, 4740, 4.0),
 (16445, 5263, 4.0),
 (31264, 9550, 3.0),
 (25819, 4942, 3.0),
 (47086, 7826, 4.0),
 (800, 7305, 5.0),
 (39241, 6876, 4.0),
 (43719, 5406, 1.0),
 (26302, 5020, 4.0),
 (31860, 4705, 5.0),
 (27534, 4777, 5.0),
 (29418, 1056, 4.0),
 (48148, 1880, 1.0),
 (29973, 720, 4.0),
 (13068, 5255, 4.0),
 (22192, 1993, 2.0),
 (30691, 1462, 4.0),
 (49521, 9729, 4.0),
 (7406, 1398, 1.0),
 (36240, 209, 5.0),
 (49130, 3893, 3.0),
 (48697, 8436, 4.0),
 (50317, 5181, 5.0),
 (21552, 4213, 4.0),
 (3080, 3492, 3.0),
 (20003, 2545, 4.0),
 (575, 2554, 5.0),
 (6630, 3790, 4.0),
 (35318, 2718, 5.0),
 (39266, 609, 4.0),
 (48449, 5042, 3.0),
 (44229, 9030, 3.0),
 (26314, 7779, 4.0),
 (22625, 975, 3.0),
 (18120, 1159, 3.0),
 (12734, 299, 2.0),
 (22164, 757, 4.0),
 (9953, 3640, 4.0),
 (1572, 8901, 3.0),
 (34384, 7492, 3.0),
 (15752, 8473, 1.0),
 (39195, 1096, 5.0),
 (21217, 727, 3.0),
 (48605, 9864, 3.0),
 (30833, 381, 3.0),
 (50563, 9779, 4.0),
 (11259, 5048, 3.0),
 (52135, 5238, 3.0),
 (1843, 6067, 4.0),
 (23024, 2083, 3.0),
 (2763, 4746, 2.0),
 (12387, 4788, 4.0),
 (30064, 5609, 4.0),
 (26371, 3471, 5.0),

In [23]:
# Keep plain DataFrames for evaluation helpers that need them
train_df = ratings_filtered.sample(frac=0.8, random_state=42)
test_df  = ratings_filtered.drop(train_df.index)

In [24]:
train_df

        book_id  user_id  rating
224336     2245    39445       5
390442     3910    25368       4
217756     2179    48234       5
771881     7779    39520       3
884748     8957    37947       4
...         ...      ...     ...
335889     3363    16821       5
891153     9026     2182       3
351482     3519    47968       5
255984     2562    33982       5
528904     5306    14001       4

[687677 rows x 3 columns]

In [25]:
test_df

        book_id  user_id  rating
3             1     1169       4
5             1     2077       4
8             1     3662       4
13            1     6630       5
15            1     9246       1
...         ...      ...     ...
981640     9999    33261       2
981642     9999    35005       3
981653     9999    42893       4
981654     9999    45918       5
981656     9999    50041       4

[171919 rows x 3 columns]

In [26]:
# Train Surprise SVD
svd_model = SVD(n_factors=100, n_epochs=20, lr_all=0.005, reg_all=0.02, random_state=42)
svd_model.fit(trainset)

In [27]:
svd_model

In [28]:
# Evaluate with Surprise's built-in metrics
predictions = svd_model.test(testset)
print(f"CF Test RMSE : {accuracy.rmse(predictions, verbose=False):.4f}")
print(f"CF Test MAE  : {accuracy.mae(predictions,  verbose=False):.4f}")

CF Test RMSE : 0.8439
CF Test MAE  : 0.6606

In [29]:
# Pre-cache: all unique book IDs known to the CF model (inner ids)
cf_all_book_ids = list(ratings_filtered['book_id'].unique())

In [30]:
cf_all_book_ids

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 46,
 47,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 410,
 411,
 412,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 554,
 555,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 739,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 789,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 914,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 959,
 960,
 961,
 962,
 964,
 965,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 987,
 988,
 989,
 990,
 991,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 ...]

## mlflow tracking

In [31]:
param_grid = {
    'n_factors':  [50, 100, 150],      # size of latent factor space
    'n_epochs':   [10, 20],            # SGD passes over the training data
    'lr_all':     [0.002, 0.005],      # learning rate for all parameters
    'reg_all':    [0.02, 0.1],         # L2 regularisation strength
}

In [32]:
import itertools

keys   = list(param_grid.keys())
combos = [dict(zip(keys, vals)) for vals in itertools.product(*param_grid.values())]
print(f"Running {len(combos)} experiments...\n")

Running 24 experiments...

In [33]:
import mlflow
import mlflow.sklearn

EXPERIMENT_NAME = "SVD_Collaborative_Filtering"
mlflow.set_experiment(EXPERIMENT_NAME)
 
best_rmse  = float('inf')
best_run_id = None
best_model  = None
best_params = None

In [34]:
for i, params in enumerate(combos, 1):
    run_name = (
        f"svd_f{params['n_factors']}_e{params['n_epochs']}"
        f"_lr{params['lr_all']}_reg{params['reg_all']}"
    )
    print(f"[{i:>2}/{len(combos)}] {run_name}")
 
    with mlflow.start_run(run_name=run_name):
 
        # ── Log hyperparameters ───────────────────────────────────────────
        mlflow.log_params(params)
        mlflow.log_param("test_size",    0.2)
        mlflow.log_param("random_state", 42)
 
        # ── Train ─────────────────────────────────────────────────────────
        model = SVD(
            n_factors = params['n_factors'],
            n_epochs  = params['n_epochs'],
            lr_all    = params['lr_all'],
            reg_all   = params['reg_all'],
            random_state = 42,
        )
        model.fit(trainset)
 
        # ── Evaluate ──────────────────────────────────────────────────────
        predictions = model.test(testset)
        rmse = accuracy.rmse(predictions, verbose=False)
        mae  = accuracy.mae(predictions,  verbose=False)
 
        # Coverage: fraction of (user, item) pairs the model can predict
        # (always 1.0 for SVD, useful baseline to log for other model types)
        n_users = trainset.n_users
        n_items = trainset.n_items
 
        # Bias magnitudes — useful for diagnosing over/underfitting
        user_bias_mean = float(np.abs(model.bu).mean())
        item_bias_mean = float(np.abs(model.bi).mean())
 
        # ── Log metrics ───────────────────────────────────────────────────
        mlflow.log_metrics({
            "rmse":            round(rmse, 4),
            "mae":             round(mae,  4),
            "n_users":         n_users,
            "n_items":         n_items,
            "user_bias_mean":  round(user_bias_mean, 4),
            "item_bias_mean":  round(item_bias_mean, 4),
        })
 
        # ── Log model artifact (best run only to save disk space) ─────────
        run_id = mlflow.active_run().info.run_id
        if rmse < best_rmse:
            best_rmse   = rmse
            best_run_id = run_id
            best_model  = model
            best_params = params
            mlflow.log_param("is_best", True)
        else:
            mlflow.log_param("is_best", False)
 
        print(f"         RMSE={rmse:.4f}  MAE={mae:.4f}")

[ 1/24] svd_f50_e10_lr0.002_reg0.02
         RMSE=0.8690  MAE=0.6904
[ 2/24] svd_f50_e10_lr0.002_reg0.1
         RMSE=0.8697  MAE=0.6916
[ 3/24] svd_f50_e10_lr0.005_reg0.02
         RMSE=0.8479  MAE=0.6676
[ 4/24] svd_f50_e10_lr0.005_reg0.1
         RMSE=0.8474  MAE=0.6690
[ 5/24] svd_f50_e20_lr0.002_reg0.02
         RMSE=0.8518  MAE=0.6722
[ 6/24] svd_f50_e20_lr0.002_reg0.1
         RMSE=0.8517  MAE=0.6736
[ 7/24] svd_f50_e20_lr0.005_reg0.02
         RMSE=0.8404  MAE=0.6575
[ 8/24] svd_f50_e20_lr0.005_reg0.1
         RMSE=0.8383  MAE=0.6585
[ 9/24] svd_f100_e10_lr0.002_reg0.02
         RMSE=0.8721  MAE=0.6932
[10/24] svd_f100_e10_lr0.002_reg0.1
         RMSE=0.8720  MAE=0.6937
[11/24] svd_f100_e10_lr0.005_reg0.02
         RMSE=0.8511  MAE=0.6704
[12/24] svd_f100_e10_lr0.005_reg0.1
         RMSE=0.8490  MAE=0.6704
[13/24] svd_f100_e20_lr0.002_reg0.02
         RMSE=0.8549  MAE=0.6751
[14/24] svd_f100_e20_lr0.002_reg0.1
         RMSE=0.8534  MAE=0.6752
[15/24] svd_f100_e20_lr0.005_reg0.02
         RMSE=0.8439  MAE=0.6606
[16/24] svd_f100_e20_lr0.005_reg0.1
         RMSE=0.8389  MAE=0.6593
[17/24] svd_f150_e10_lr0.002_reg0.02
         RMSE=0.8754  MAE=0.6962
[18/24] svd_f150_e10_lr0.002_reg0.1
         RMSE=0.8745  MAE=0.6959
[19/24] svd_f150_e10_lr0.005_reg0.02
         RMSE=0.8544  MAE=0.6733
[20/24] svd_f150_e10_lr0.005_reg0.1
         RMSE=0.8506  MAE=0.6720
[21/24] svd_f150_e20_lr0.002_reg0.02
         RMSE=0.8584  MAE=0.6780
[22/24] svd_f150_e20_lr0.002_reg0.1
         RMSE=0.8554  MAE=0.6770
[23/24] svd_f150_e20_lr0.005_reg0.02
         RMSE=0.8474  MAE=0.6636
[24/24] svd_f150_e20_lr0.005_reg0.1
         RMSE=0.8397  MAE=0.6601

In [35]:
import pickle

print(f"\n{'='*55}")
print(f"  Best run  : {best_run_id}")
print(f"  Best RMSE : {best_rmse:.4f}")
print(f"  Params    : {best_params}")
print(f"{'='*55}\n")
 
# Log the best model artifact back into its own run
with mlflow.start_run(run_id=best_run_id):
    # Save with pickle so trainset is preserved (avoids score drift on reload)
    with open('svd_best_model.pkl', 'wb') as f:
        pickle.dump(best_model, f)
    mlflow.log_artifact('svd_best_model.pkl', artifact_path='model')
    print("Best model saved to 'svd_best_model.pkl' and logged as MLflow artifact.")

=======================================================
  Best run  : a3cb5ca4de3144db93fc991d84b75cec
  Best RMSE : 0.8383
  Params    : {'n_factors': 50, 'n_epochs': 20, 'lr_all': 0.005, 'reg_all': 0.1}
=======================================================

Best model saved to 'svd_best_model.pkl' and logged as MLflow artifact.

In [36]:
client  = mlflow.tracking.MlflowClient()
exp     = client.get_experiment_by_name(EXPERIMENT_NAME)
runs    = client.search_runs(
    experiment_ids=[exp.experiment_id],
    order_by=["metrics.rmse ASC"]
)
 
rows = []
for r in runs:
    p = r.data.params
    m = r.data.metrics
    rows.append({
        "run_name":   r.info.run_name,
        "n_factors":  p.get("n_factors"),
        "n_epochs":   p.get("n_epochs"),
        "lr_all":     p.get("lr_all"),
        "reg_all":    p.get("reg_all"),
        "RMSE":       round(m.get("rmse", 0), 4),
        "MAE":        round(m.get("mae",  0), 4),
        "is_best":    p.get("is_best"),
    })
 
summary = pd.DataFrame(rows)
print("\nAll runs (sorted by RMSE):")
print(summary.to_string(index=False))
print(f"\nRun `mlflow ui` to explore results in the browser.")

All runs (sorted by RMSE):
                    run_name n_factors n_epochs lr_all reg_all   RMSE    MAE is_best
  svd_f50_e20_lr0.005_reg0.1        50       20  0.005     0.1 0.8383 0.6585    True
  svd_f50_e20_lr0.005_reg0.1        50       20  0.005     0.1 0.8383 0.6585    True
 svd_f100_e20_lr0.005_reg0.1       100       20  0.005     0.1 0.8389 0.6593   False
 svd_f100_e20_lr0.005_reg0.1       100       20  0.005     0.1 0.8389 0.6593   False
 svd_f150_e20_lr0.005_reg0.1       150       20  0.005     0.1 0.8397 0.6601   False
 svd_f150_e20_lr0.005_reg0.1       150       20  0.005     0.1 0.8397 0.6601   False
 svd_f50_e20_lr0.005_reg0.02        50       20  0.005    0.02 0.8404 0.6575    True
 svd_f50_e20_lr0.005_reg0.02        50       20  0.005    0.02 0.8404 0.6575    True
svd_f100_e20_lr0.005_reg0.02       100       20  0.005    0.02 0.8439 0.6606   False
svd_f100_e20_lr0.005_reg0.02       100       20  0.005    0.02 0.8439 0.6606   False
svd_f150_e20_lr0.005_reg0.02       150       20  0.005    0.02 0.8474 0.6636   False
  svd_f50_e10_lr0.005_reg0.1        50       10  0.005     0.1 0.8474 0.6690    True
svd_f150_e20_lr0.005_reg0.02       150       20  0.005    0.02 0.8474 0.6636   False
  svd_f50_e10_lr0.005_reg0.1        50       10  0.005     0.1 0.8474 0.6690    True
 svd_f50_e10_lr0.005_reg0.02        50       10  0.005    0.02 0.8479 0.6676    True
 svd_f50_e10_lr0.005_reg0.02        50       10  0.005    0.02 0.8479 0.6676    True
 svd_f100_e10_lr0.005_reg0.1       100       10  0.005     0.1 0.8490 0.6704   False
 svd_f100_e10_lr0.005_reg0.1       100       10  0.005     0.1 0.8490 0.6704   False
 svd_f150_e10_lr0.005_reg0.1       150       10  0.005     0.1 0.8506 0.6720   False
 svd_f150_e10_lr0.005_reg0.1       150       10  0.005     0.1 0.8506 0.6720   False
svd_f100_e10_lr0.005_reg0.02       100       10  0.005    0.02 0.8511 0.6704   False
svd_f100_e10_lr0.005_reg0.02       100       10  0.005    0.02 0.8511 0.6704   False
  svd_f50_e20_lr0.002_reg0.1        50       20  0.002     0.1 0.8517 0.6736   False
  svd_f50_e20_lr0.002_reg0.1        50       20  0.002     0.1 0.8517 0.6736   False
 svd_f50_e20_lr0.002_reg0.02        50       20  0.002    0.02 0.8518 0.6722   False
 svd_f50_e20_lr0.002_reg0.02        50       20  0.002    0.02 0.8518 0.6722   False
 svd_f100_e20_lr0.002_reg0.1       100       20  0.002     0.1 0.8534 0.6752   False
 svd_f100_e20_lr0.002_reg0.1       100       20  0.002     0.1 0.8534 0.6752   False
svd_f150_e10_lr0.005_reg0.02       150       10  0.005    0.02 0.8544 0.6733   False
svd_f150_e10_lr0.005_reg0.02       150       10  0.005    0.02 0.8544 0.6733   False
svd_f100_e20_lr0.002_reg0.02       100       20  0.002    0.02 0.8549 0.6751   False
svd_f100_e20_lr0.002_reg0.02       100       20  0.002    0.02 0.8549 0.6751   False
 svd_f150_e20_lr0.002_reg0.1       150       20  0.002     0.1 0.8554 0.6770   False
 svd_f150_e20_lr0.002_reg0.1       150       20  0.002     0.1 0.8554 0.6770   False
svd_f150_e20_lr0.002_reg0.02       150       20  0.002    0.02 0.8584 0.6780   False
svd_f150_e20_lr0.002_reg0.02       150       20  0.002    0.02 0.8584 0.6780   False
 svd_f50_e10_lr0.002_reg0.02        50       10  0.002    0.02 0.8690 0.6904    True
 svd_f50_e10_lr0.002_reg0.02        50       10  0.002    0.02 0.8690 0.6904    True
  svd_f50_e10_lr0.002_reg0.1        50       10  0.002     0.1 0.8697 0.6916   False
  svd_f50_e10_lr0.002_reg0.1        50       10  0.002     0.1 0.8697 0.6916   False
 svd_f100_e10_lr0.002_reg0.1       100       10  0.002     0.1 0.8720 0.6937   False
 svd_f100_e10_lr0.002_reg0.1       100       10  0.002     0.1 0.8720 0.6937   False
svd_f100_e10_lr0.002_reg0.02       100       10  0.002    0.02 0.8721 0.6932   False
svd_f100_e10_lr0.002_reg0.02       100       10  0.002    0.02 0.8721 0.6932   False
 svd_f150_e10_lr0.002_reg0.1       150       10  0.002     0.1 0.8745 0.6959   False
 svd_f150_e10_lr0.002_reg0.1       150       10  0.002     0.1 0.8745 0.6959   False
svd_f150_e10_lr0.002_reg0.02       150       10  0.002    0.02 0.8754 0.6962   False
svd_f150_e10_lr0.002_reg0.02       150       10  0.002    0.02 0.8754 0.6962   False

Run `mlflow ui` to explore results in the browser.

# hybrid

## functions

In [3]:
def get_cf_scores(user_id):
    """
    Return {book_id: normalized_cf_score} using Surprise SVD predictions.
    Surprise predicts on the 1-5 scale; we normalize to [0, 1] for blending.
    Unknown users return an empty dict (triggers CBF fallback).
    """
    # Check if user exists in the trainset
    try:
        svd_model.trainset.to_inner_uid(user_id)
    except ValueError:
        return {}

    raw_scores = {
        bid: svd_model.predict(user_id, bid).est
        for bid in cf_all_book_ids
    }
    vals   = np.array(list(raw_scores.values()))
    mn, mx = vals.min(), vals.max()
    normed = (vals - mn) / (mx - mn) if mx != mn else np.zeros_like(vals)
    return {bid: float(normed[i]) for i, bid in enumerate(raw_scores)}

In [4]:
def get_cbf_scores(title):
    """Return {book_id: normalized_cbf_score} for every CBF book."""
    if title not in cbf_title_to_idx:
        return {}
    idx    = cbf_title_to_idx[title]
    sims   = cbf_sim_matrix[idx]
    mn, mx = sims.min(), sims.max()
    normed = (sims - mn) / (mx - mn) if mx != mn else np.zeros_like(sims)
    return {cbf_df.iloc[i]['book_id']: normed[i] for i in range(len(normed))}

In [5]:
def recommend_hybrid(user_id, seed_title, n=10, alpha=0.5):
    """
    Blend CBF (Word2Vec cosine similarity) and CF (SVD) recommendations.

    Parameters
    ----------
    user_id    : int   – target user
    seed_title : str   – anchor book for content similarity
    n          : int   – number of results to return
    alpha      : float – CF weight (0 = pure CBF, 1 = pure CF)

    Returns
    -------
    DataFrame [Title, Authors, CF_Score, CBF_Score, Hybrid_Score]
    """
    cf_scores  = get_cf_scores(user_id)
    cbf_scores = get_cbf_scores(seed_title)

    if not cf_scores and not cbf_scores:
        return "User ID and book title both not found."
    if not cf_scores:
        print("⚠️  User not found — falling back to pure CBF.")
        alpha = 0.0
    if not cbf_scores:
        print("⚠️  Seed title not found — falling back to pure CF.")
        alpha = 1.0

    read_book_ids = set(ratings_filtered[ratings_filtered['user_id'] == user_id]['book_id'])
    all_book_ids  = set(cf_scores) | set(cbf_scores)

    results = []
    for bid in all_book_ids:
        if bid in read_book_ids:
            continue

        cf_s   = cf_scores.get(bid, 0.0)
        cbf_s  = cbf_scores.get(bid, 0.0)
        hybrid = alpha * cf_s + (1 - alpha) * cbf_s

        book_row = books[books['book_id'] == bid]
        if book_row.empty:
            book_row = books[books['id'] == bid]
        if book_row.empty:
            continue

        results.append({
            "Title":        book_row['title'].values[0],
            "Authors":      book_row['authors'].values[0],
            "CF_Score":     round(cf_s,   4),
            "CBF_Score":    round(cbf_s,  4),
            "Hybrid_Score": round(hybrid, 4),
        })

    if not results:
        return "No recommendations found."

    result_df = (
        pd.DataFrame(results)
        .sort_values("Hybrid_Score", ascending=False)
        .head(n)
        .reset_index(drop=True)
    )
    result_df.index += 1
    return result_df

## evaluation

In [6]:
def _get_hybrid_ranked_list(user_id, seed_title, alpha, n_candidates=100):
    """
    Internal helper: returns a ranked list of book_ids for evaluation.
    Does NOT filter already-read books (that's handled by the test split).
    """
    cf_scores  = get_cf_scores(user_id)
    cbf_scores = get_cbf_scores(seed_title)
    if not cf_scores and not cbf_scores:
        return []

    eff_alpha = alpha
    if not cf_scores:  eff_alpha = 0.0
    if not cbf_scores: eff_alpha = 1.0

    all_book_ids = set(cf_scores) | set(cbf_scores)
    scored = [
        (bid, eff_alpha * cf_scores.get(bid, 0.0) +
              (1 - eff_alpha) * cbf_scores.get(bid, 0.0))
        for bid in all_book_ids
    ]
    scored.sort(key=lambda x: x[1], reverse=True)
    return [bid for bid, _ in scored[:n_candidates]]


def ndcg_at_k(recommended, relevant_set, k):
    """
    Normalised Discounted Cumulative Gain @ k.

    Uses binary relevance (1 if book is in relevant_set, else 0).
    IDCG assumes all relevant items are placed at the top ranks.
    """
    dcg = sum(
        1.0 / np.log2(rank + 1)
        for rank, bid in enumerate(recommended[:k], start=1)
        if bid in relevant_set
    )
    n_relevant = min(len(relevant_set), k)
    idcg = sum(1.0 / np.log2(rank + 1) for rank in range(1, n_relevant + 1))
    return dcg / idcg if idcg > 0 else 0.0


def precision_at_k(recommended, relevant_set, k):
    """Fraction of top-k recommendations that are relevant."""
    hits = sum(1 for bid in recommended[:k] if bid in relevant_set)
    return hits / k


def recall_at_k(recommended, relevant_set, k):
    """Fraction of all relevant items that appear in top-k."""
    if not relevant_set:
        return 0.0
    hits = sum(1 for bid in recommended[:k] if bid in relevant_set)
    return hits / len(relevant_set)


def hit_rate_at_k(recommended, relevant_set, k):
    """1 if at least one relevant item is in top-k, else 0."""
    return 1.0 if any(bid in relevant_set for bid in recommended[:k]) else 0.0


def average_precision_at_k(recommended, relevant_set, k):
    """
    Average Precision @ k.
    AP = mean of precision@i for every rank i where item i is relevant.
    Rewards systems that place relevant items earlier in the list.
    """
    hits, score = 0, 0.0
    for rank, bid in enumerate(recommended[:k], start=1):
        if bid in relevant_set:
            hits += 1
            score += hits / rank
    return score / min(len(relevant_set), k) if relevant_set else 0.0


def evaluate_hybrid(alpha=0.5, k_values=(5, 10, 20),
                    relevance_threshold=4, n_test_users=200,
                    min_test_relevant=2, random_state=42):
    """
    Evaluate the hybrid recommender on the held-out test split.

    Strategy
    --------
    For each sampled test user:
      - Ground truth = their test-set books rated >= relevance_threshold.
      - CBF seed     = their highest-rated book in the training split.
      - Rank all candidate books with the hybrid, compute metrics.

    Parameters
    ----------
    alpha               : float – CF weight (0=pure CBF, 1=pure CF)
    k_values            : tuple – cut-off ranks to evaluate
    relevance_threshold : int   – min rating to count as "liked"
    n_test_users        : int   – users to sample (speed vs. accuracy)
    min_test_relevant   : int   – skip users with fewer relevant test items
    random_state        : int   – reproducible sampling

    Returns
    -------
    summary   : dict  {metric: {k: mean_score}}
    detail_df : DataFrame with per-user scores (for deeper inspection)
    """
    rng = np.random.default_rng(random_state)

    train_users = set(train_df['user_id'].unique())
    test_users  = set(test_df['user_id'].unique())
    eligible    = list(train_users & test_users)
    rng.shuffle(eligible)
    eligible    = eligible[:n_test_users]

    # Best training-set book per user (used as CBF seed)
    train_top = (
        train_df.sort_values('rating', ascending=False)
        .groupby('user_id').first().reset_index()
    )[['user_id', 'book_id']]
    uid_to_seed_bid = dict(zip(train_top['user_id'], train_top['book_id']))
    rows = []
    for uid in eligible:
        user_test = test_df[test_df['user_id'] == uid]
        relevant  = set(
            user_test[user_test['rating'] >= relevance_threshold]['book_id']
        )
        if len(relevant) < min_test_relevant:
            continue

        seed_bid   = uid_to_seed_bid.get(uid)
        seed_match = cbf_df[cbf_df['book_id'] == seed_bid]['title']
        seed_title = seed_match.values[0] if not seed_match.empty else ""

        recommended = _get_hybrid_ranked_list(
            uid, seed_title, alpha, n_candidates=500
        )

        row = {"user_id": uid, "n_relevant": len(relevant)}
        for k in k_values:
            row[f"NDCG@{k}"] = ndcg_at_k(recommended, relevant, k)
            row[f"P@{k}"]    = precision_at_k(recommended, relevant, k)
            row[f"R@{k}"]    = recall_at_k(recommended, relevant, k)
            row[f"HR@{k}"]   = hit_rate_at_k(recommended, relevant, k)
            row[f"MAP@{k}"]  = average_precision_at_k(recommended, relevant, k)
        rows.append(row)

    if not rows:
        print("No eligible users found for evaluation.")
        return {}, pd.DataFrame()

    detail_df   = pd.DataFrame(rows)
    metric_cols = [c for c in detail_df.columns if c not in ('user_id', 'n_relevant')]
    means       = detail_df[metric_cols].mean()

    summary = {}
    for k in k_values:
        for metric in ('NDCG', 'P', 'R', 'HR', 'MAP'):
            summary.setdefault(metric, {})[k] = round(means[f"{metric}@{k}"], 4)

    return summary, detail_df
  
def print_evaluation_report(alpha=0.5, k_values=(5, 10, 20),
                             relevance_threshold=4, n_test_users=200):
    """Run evaluation and pretty-print a summary table."""
    print(f"\n{'='*62}")
    print("  HYBRID RECOMMENDER — RANKING EVALUATION REPORT")
    print(f"{'='*62}")
    print(f"  alpha={alpha}  |  threshold≥{relevance_threshold}  |  users={n_test_users}")
    print(f"{'='*62}")

    summary, detail_df = evaluate_hybrid(
        alpha=alpha, k_values=k_values,
        relevance_threshold=relevance_threshold,
        n_test_users=n_test_users
    )
    if not summary:
        return None, None

    k_header = "".join(f"{'@'+str(k):>10}" for k in k_values)
    print(f"\n{'Metric':<12}{k_header}")
    print("-" * (12 + 10 * len(k_values)))

    labels = [('NDCG','NDCG'), ('P','Precision'), ('R','Recall'),
              ('HR','Hit Rate'), ('MAP','MAP')]
    for key, label in labels:
        row = f"{label:<12}"
        for k in k_values:
            row += f"{summary[key][k]:>10.4f}"
        print(row)

    print(f"\nEvaluated on {len(detail_df)} users.")
    print("\nMetric guide:")
    print("  NDCG      – ranking quality; rewards hits ranked higher (0→1, higher=better)")
    print("  Precision – fraction of top-k that are relevant")
    print("  Recall    – fraction of relevant items found in top-k")
    print("  Hit Rate  – % of users who got ≥1 relevant item in top-k")
    print("  MAP       – mean average precision across hit positions")

    return summary, detail_df

## save artifacts

In [42]:
import pickle
import os

ARTIFACTS = {
    'cbf_sim_matrix': 'D:/..amikom/6th/data-mining-project/artifacts/cbf_sim_matrix.npy',
    'cbf_meta':       'D:/..amikom/6th/data-mining-project/artifacts/cbf_meta.pkl',
    'svd_model':      'D:/..amikom/6th/data-mining-project/artifacts/svd_model.pkl',
    'ratings_df':     'D:/..amikom/6th/data-mining-project/artifacts/ratings_filtered.pkl',
    'train_test':     'D:/..amikom/6th/data-mining-project/artifacts/train_test_split.pkl',
}

def save_artifacts():
    """
    Persist all objects needed to serve recommendations without retraining.

    Files written
    -------------
    artifacts/cbf_sim_matrix.npy   - cosine similarity matrix (float32)
    artifacts/cbf_meta.pkl         - CBF lookup dicts + cbf_df
    artifacts/svd_model.pkl        - full Surprise SVD model (incl. trainset)
    artifacts/ratings_filtered.pkl - filtered ratings DataFrame + cf_all_book_ids
    artifacts/train_test_split.pkl - train_df / test_df (for evaluation)
    """
    os.makedirs('D:/..amikom/6th/data-mining-project/artifacts', exist_ok=True)

    # Store as float32 to halve disk size (cosine sim doesn't need float64)
    np.save(ARTIFACTS['cbf_sim_matrix'], cbf_sim_matrix.astype(np.float32))

    with open(ARTIFACTS['cbf_meta'], 'wb') as f:
        pickle.dump({
            'cbf_df':           cbf_df,
            'cbf_title_to_idx': cbf_title_to_idx,
            'cbf_id_to_idx':    cbf_id_to_idx,
        }, f)

    # Plain pickle preserves trainset inside svd_model — avoids score drift on reload
    with open(ARTIFACTS['svd_model'], 'wb') as f:
        pickle.dump(svd_model, f)

    with open(ARTIFACTS['ratings_df'], 'wb') as f:
        pickle.dump({
            'ratings_filtered': ratings_filtered,
            'cf_all_book_ids':  cf_all_book_ids,
        }, f)

    with open(ARTIFACTS['train_test'], 'wb') as f:
        pickle.dump({'train_df': train_df, 'test_df': test_df}, f)

    print("Artifacts saved:")
    for name, path in ARTIFACTS.items():
        if os.path.exists(path):
            print(f"  {path:<45} {os.path.getsize(path)/1e6:.1f} MB")

save_artifacts()

Artifacts saved:
  D:/..amikom/6th/data-mining-project/artifacts/cbf_sim_matrix.npy 304.9 MB
  D:/..amikom/6th/data-mining-project/artifacts/cbf_meta.pkl 4.1 MB
  D:/..amikom/6th/data-mining-project/artifacts/svd_model.pkl 68.1 MB
  D:/..amikom/6th/data-mining-project/artifacts/ratings_filtered.pkl 27.7 MB
  D:/..amikom/6th/data-mining-project/artifacts/train_test_split.pkl 27.5 MB

## load artifacts (use this in a new session instead of retraining)

In [7]:
import pickle, os
import numpy as np

ARTIFACTS = {
    'cbf_sim_matrix': 'D:/..amikom/6th/data-mining-project/artifacts/cbf_sim_matrix.npy',
    'cbf_meta':       'D:/..amikom/6th/data-mining-project/artifacts/cbf_meta.pkl',
    'svd_model':      'D:/..amikom/6th/data-mining-project/artifacts/svd_model.pkl',
    'ratings_df':     'D:/..amikom/6th/data-mining-project/artifacts/ratings_filtered.pkl',
    'train_test':     'D:/..amikom/6th/data-mining-project/artifacts/train_test_split.pkl',
}

def load_artifacts():
    """
    Load all persisted artifacts. Call this at the top of any new session
    to skip retraining entirely.

    Returns True on success, False if any file is missing.
    """
    missing = [p for p in ARTIFACTS.values() if not os.path.exists(p)]
    if missing:
        print(f"Missing files (run save_artifacts() first): {missing}")
        return False

    global cbf_sim_matrix, cbf_df, cbf_title_to_idx, cbf_id_to_idx
    global svd_model, ratings_filtered, cf_all_book_ids, train_df, test_df

    # Reload as float64 for full precision during scoring
    cbf_sim_matrix = np.load(ARTIFACTS['cbf_sim_matrix']).astype(np.float64)

    with open(ARTIFACTS['cbf_meta'], 'rb') as f:
        meta = pickle.load(f)
    cbf_df           = meta['cbf_df']
    cbf_title_to_idx = meta['cbf_title_to_idx']
    cbf_id_to_idx    = meta['cbf_id_to_idx']

    with open(ARTIFACTS['svd_model'], 'rb') as f:
        svd_model = pickle.load(f)

    with open(ARTIFACTS['ratings_df'], 'rb') as f:
        rd = pickle.load(f)
    ratings_filtered = rd['ratings_filtered']
    cf_all_book_ids  = rd['cf_all_book_ids']

    with open(ARTIFACTS['train_test'], 'rb') as f:
        tt = pickle.load(f)
    train_df = tt['train_df']
    test_df  = tt['test_df']

    print("All artifacts loaded. Ready to serve recommendations.")
    return True

loaded = load_artifacts()

All artifacts loaded. Ready to serve recommendations.

## usage

In [45]:
print("\n" + "="*60)
print("HYBRID RECOMMENDATIONS")
print("="*60)

user_id    = 314
seed_title = "The Hunger Games (The Hunger Games, #1)"
alpha      = 0.8  # 0 = pure CBF, 1 = pure CF

recs = recommend_hybrid(user_id, seed_title, n=10, alpha=alpha)
print(f"Top 10 recommendations for user {user_id}")
print(f"Seed : '{seed_title}'")
print(f"Alpha (CF weight): {alpha}  |  CBF weight: {1-alpha}\n")
recs

============================================================
HYBRID RECOMMENDATIONS
============================================================
Top 10 recommendations for user 314
Seed : 'The Hunger Games (The Hunger Games, #1)'
Alpha (CF weight): 0.8  |  CBF weight: 0.19999999999999996

,Title,Authors,CF_Score,CBF_Score,Hybrid_Score
1,"Saga, Vol. 6 (Saga, #6)",author_brian_k_vaughan author_fiona_staples,0.9769,0.7479,0.9311
2,The Days Are Just Packed: A Calvin and Hobbes ...,author_bill_watterson,1.0000,0.5655,0.9131
3,The Complete Calvin and Hobbes,author_bill_watterson,0.9839,0.6179,0.9107
4,The Hunger Games Tribute Guide,author_emily_seife,0.8985,0.9523,0.9092
5,"Queen of Shadows (Throne of Glass, #4)",author_sarah_j_maas,0.9082,0.8876,0.9040
6,"Transmetropolitan, Vol. 5: Lonely City (Transm...",author_warren_ellis author_darick_robertson au...,0.9184,0.7873,0.8922
7,BookRags Summary: A Storm of Swords,author_bookrags,0.8935,0.8465,0.8841
8,"The Complete Maus (Maus, #1-2)",author_art_spiegelman,0.9482,0.6252,0.8836
9,"Saga, Vol. 5 (Saga, #5)",author_brian_k_vaughan author_fiona_staples,0.9210,0.7312,0.8831
10,"Saga, Vol. 1 (Saga, #1)",author_brian_k_vaughan author_fiona_staples,0.9018,0.8052,0.8825

In [11]:
print("\n" + "="*60)
print("HYBRID RECOMMENDATIONS")
print("="*60)

user_id    = 314
seed_title = "The Hunger Games (The Hunger Games, #1)"
alpha      = 0.8  # 0 = pure CBF, 1 = pure CF

recs = recommend_hybrid(user_id, seed_title, n=10, alpha=alpha)
print(f"Top 10 recommendations for user {user_id}")
print(f"Seed : '{seed_title}'")
print(f"Alpha (CF weight): {alpha}  |  CBF weight: {1-alpha}\n")
recs

============================================================
HYBRID RECOMMENDATIONS
============================================================
Top 10 recommendations for user 314
Seed : 'The Hunger Games (The Hunger Games, #1)'
Alpha (CF weight): 0.8  |  CBF weight: 0.19999999999999996

,Title,Authors,CF_Score,CBF_Score,Hybrid_Score
1,Peter and the Shadow Thieves (Peter and the St...,author_dave_barry author_ridley_pearson author...,0.8918,0.7938,0.8722
2,"American Gods (American Gods, #1)",author_neil_gaiman,0.8303,0.9471,0.8536
3,"The Salmon of Doubt (Dirk Gently, #3)",author_douglas_adams,0.8470,0.7774,0.8331
4,Still Life with Woodpecker,author_tom_robbins,0.8961,0.4988,0.8167
5,Prophet,author_frank_e_peretti,0.8641,0.6239,0.8161
6,Children of Dune (Dune Chronicles #3),author_frank_herbert,0.8133,0.8105,0.8128
7,"Three Men in a Boat (Three Men, #1)",author_jerome_k_jerome,0.8867,0.5158,0.8125
8,The Curious Incident of the Dog in the Night-Time,author_mark_haddon,0.8311,0.6950,0.8038
9,Deerskin,author_robin_mckinley,0.7766,0.9010,0.8015
10,The Days Are Just Packed: A Calvin and Hobbes ...,author_bill_watterson,1.0000,0.0000,0.8000

In [46]:
# ── Ranking evaluation ──────────────────────────────────────────────
summary, detail_df = print_evaluation_report(
    alpha=alpha,
    k_values=(5, 10, 20),
    relevance_threshold=4,   # ratings 4-5 = "relevant"
    n_test_users=200
)

==============================================================
  HYBRID RECOMMENDER — RANKING EVALUATION REPORT
==============================================================
  alpha=0.8  |  threshold≥4  |  users=200
==============================================================

Metric              @5       @10       @20
------------------------------------------
NDCG            0.0060    0.0046    0.0052
Precision       0.0064    0.0032    0.0021
Recall          0.0055    0.0055    0.0070
Hit Rate        0.0319    0.0319    0.0426
MAP             0.0025    0.0016    0.0016

Evaluated on 94 users.

Metric guide:
  NDCG      – ranking quality; rewards hits ranked higher (0→1, higher=better)
  Precision – fraction of top-k that are relevant
  Recall    – fraction of relevant items found in top-k
  Hit Rate  – % of users who got ≥1 relevant item in top-k
  MAP       – mean average precision across hit positions

In [47]:
# Optional: compare alpha values
print("\n── Alpha sensitivity (NDCG@10) ──")
for a in (0.0, 0.25, 0.5, 0.75, 1.0):
    s, _ = evaluate_hybrid(alpha=a, k_values=(10,), n_test_users=100)
    if s:
        print(f"  alpha={a:.2f}  NDCG@10={s['NDCG'][10]:.4f}  HR@10={s['HR'][10]:.4f}")

── Alpha sensitivity (NDCG@10) ──
  alpha=0.00  NDCG@10=0.0102  HR@10=0.0638
  alpha=0.25  NDCG@10=0.0118  HR@10=0.0638
  alpha=0.50  NDCG@10=0.0059  HR@10=0.0426
  alpha=0.75  NDCG@10=0.0023  HR@10=0.0213
  alpha=1.00  NDCG@10=0.0000  HR@10=0.0000